version: 2
registries:
  nuget-feed-default:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
    
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly

- package-ecosystem: npm
  directory: "/Source/Blazorise"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Blazorise.AntDesign"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Blazorise.Bootstrap"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Blazorise.Bootstrap5"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Blazorise.Bulma"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Blazorise.Frolic"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Blazorise.Material"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Blazorise.Tailwind"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.Animations"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.Charts"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.Charts.DataLabels"
  schedule:
    interval: daily
    
- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.Charts.Streaming"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.Charts.Trendline"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.Components"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.Cropper"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.DataGrid"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.FluentValidation"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.Icons.Bootstrap"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.Icons.FontAwesome"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.Icons.Material"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.LoadingIndicator"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.LottieAnimation"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.Markdown"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.QRCode"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.RichTextEdit"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.Sidebar"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.Snackbar"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.SpinKit"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.TreeView"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/Source/Extensions/Blazorise.Video"
  schedule:
    interval: daily
