# These are supported funding model platforms

github: megabit
patreon: mladenmacanovic
open_collective: blazorise
ko_fi: mladenmacanovic
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://www.paypal.me/mladenmacanovic
