# Configuration for Label Actions - https://github.com/dessant/label-actions

"Status: Repro Missing":
  comment: >
    Hello @{issue-author},
    thank you for your submission. The issue was labeled "Status: Repro Missing", as you have not provided a way to reproduce the issue quickly. Most problems already solve themselves when isolated, but we would like you to provide us with a reproducible code to make it easier to investigate a possible bug.
