<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="..\..\..\Build\Blazorise.props" />

  <PropertyGroup>
    <PackageTags>blazorise blazor components reporting reports designer viewer</PackageTags>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Blazorise\Blazorise.csproj" />
    <ProjectReference Include="..\Blazorise.CodeEditor\Blazorise.CodeEditor.csproj" />
    <ProjectReference Include="..\Blazorise.Pdf\Blazorise.Pdf.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Localization\Report\*.json" />
  </ItemGroup>

</Project>