cd /d "%~dp0"

rd /s /q Source\Blazorise\bin
rd /s /q Source\Blazorise\obj
rd /s /q Source\Blazorise.Bootstrap\bin
rd /s /q Source\Blazorise.Bootstrap\obj
rd /s /q Source\Blazorise.Material\bin
rd /s /q Source\Blazorise.Material\obj
rd /s /q Source\Blazorise.Bulma\bin
rd /s /q Source\Blazorise.Bulma\obj
rd /s /q Source\Blazorise.Frolic\bin
rd /s /q Source\Blazorise.Frolic\obj
rd /s /q Source\Blazorise.AntDesign\bin
rd /s /q Source\Blazorise.AntDesign\obj
rd /s /q Source\Extensions\Blazorise.Charts\bin
rd /s /q Source\Extensions\Blazorise.Charts\obj
rd /s /q Source\Extensions\Blazorise.Charts.Streaming\bin
rd /s /q Source\Extensions\Blazorise.Charts.Streaming\obj
rd /s /q Source\Extensions\Blazorise.Components\bin
rd /s /q Source\Extensions\Blazorise.Components\obj
rd /s /q Source\Extensions\Blazorise.DataGrid\bin
rd /s /q Source\Extensions\Blazorise.DataGrid\obj
rd /s /q Source\Extensions\Blazorise.Sidebar\bin
rd /s /q Source\Extensions\Blazorise.Sidebar\obj
rd /s /q Source\Extensions\Blazorise.Snackbar\bin
rd /s /q Source\Extensions\Blazorise.Snackbar\obj
rd /s /q Source\Extensions\Blazorise.Icons.FontAwesome\bin
rd /s /q Source\Extensions\Blazorise.Icons.FontAwesome\obj
rd /s /q Source\Extensions\Blazorise.Icons.Material\bin
rd /s /q Source\Extensions\Blazorise.Icons.Material\obj

rd /s /q Demos\Apps\TodoApp\bin
rd /s /q Demos\Apps\TodoApp\obj
rd /s /q Demos\Blazorise.Demo\bin
rd /s /q Demos\Blazorise.Demo\obj
rd /s /q Demos\Blazorise.Demo.AntDesign\bin
rd /s /q Demos\Blazorise.Demo.AntDesign\obj
rd /s /q Demos\Blazorise.Demo.AntDesign.Server\bin
rd /s /q Demos\Blazorise.Demo.AntDesign.Server\obj
rd /s /q Demos\Blazorise.Demo.Bootstrap\bin
rd /s /q Demos\Blazorise.Demo.Bootstrap\obj
rd /s /q Demos\Blazorise.Demo.Bootstrap.Server\bin
rd /s /q Demos\Blazorise.Demo.Bootstrap.Server\obj
rd /s /q Demos\Blazorise.Demo.Bootstrap.RC\bin
rd /s /q Demos\Blazorise.Demo.Bootstrap.RC\obj
rd /s /q Demos\Blazorise.Demo.Bulma\bin
rd /s /q Demos\Blazorise.Demo.Bulma\obj
rd /s /q Demos\Blazorise.Demo.Bulma.Server\bin
rd /s /q Demos\Blazorise.Demo.Bulma.Server\obj
rd /s /q Demos\Blazorise.Demo.Material\bin
rd /s /q Demos\Blazorise.Demo.Material\obj
rd /s /q Demos\Blazorise.Demo.Material.Server\bin
rd /s /q Demos\Blazorise.Demo.Material.Server\obj
rd /s /q Demos\Blazorise.Demo.Frolic\bin
rd /s /q Demos\Blazorise.Demo.Frolic\obj
rd /s /q Demos\Blazorise.Demo.Frolic.Server\bin
rd /s /q Demos\Blazorise.Demo.Frolic.Server\obj

rd /s /q Tests\BasicTestApp.Client\bin
rd /s /q Tests\BasicTestApp.Client\obj
rd /s /q Tests\BasicTestApp.Server\bin
rd /s /q Tests\BasicTestApp.Server\obj
rd /s /q Tests\Blazorise.E2ETests\bin
rd /s /q Tests\Blazorise.E2ETests\obj