<Project>
  <PropertyGroup>
    <PrimaryTargetFramework>net11.0</PrimaryTargetFramework>
    <Configurations>Debug;DebugNet11;Release</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'DebugNet11'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
    <DebuggerSupport>true</DebuggerSupport>
    <MetadataUpdaterSupport>true</MetadataUpdaterSupport>
    <EnableHotReloadInRuntimeConfigDevFile>true</EnableHotReloadInRuntimeConfigDevFile>
    <WasmEnableHotReload>true</WasmEnableHotReload>
  </PropertyGroup>
</Project>