//-----------------------------------------------------------------------
// This file is autogenerated by Blazorise.Docs.Compiler
// Any changes to this file will be overwritten on build
// <auto-generated />
//-----------------------------------------------------------------------

namespace Blazorise.Docs.Models
{
    public static partial class Snippets
    {
        public const string BasicAccordionExample = @"<Accordion>
    <Collapse Visible=""@collapse1Visible"">
        <CollapseHeader>
            <Heading Size=""HeadingSize.Is5"">
                <Button Clicked=""@(()=>collapse1Visible = !collapse1Visible)"">Switch 1</Button>
            </Heading>
        </CollapseHeader>
        <CollapseBody>
            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
        </CollapseBody>
    </Collapse>
    <Collapse Visible=""@collapse2Visible"">
        <CollapseHeader>
            <Heading Size=""HeadingSize.Is5"">
                <Button Clicked=""@(()=>collapse2Visible = !collapse2Visible)"">Switch 2</Button>
            </Heading>
        </CollapseHeader>
        <CollapseBody>
            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
        </CollapseBody>
    </Collapse>
    <Collapse Visible=""@collapse3Visible"">
        <CollapseHeader>
            <Heading Size=""HeadingSize.Is5"">
                <Button Clicked=""@(()=>collapse3Visible = !collapse3Visible)"">Switch 3</Button>
            </Heading>
        </CollapseHeader>
        <CollapseBody>
            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
        </CollapseBody>
    </Collapse>
</Accordion>
@code{
    bool collapse1Visible = true;
    bool collapse2Visible = false;
    bool collapse3Visible = false;
}";

        public const string ButtonAddonExample = @"<Addons>
    <Addon AddonType=""AddonType.Body"">
        <TextEdit Placeholder=""Recipient's username"" />
    </Addon>
    <Addon AddonType=""AddonType.End"">
        <Button Color=""Color.Secondary"">Button</Button>
    </Addon>
</Addons>";

        public const string DropdownAddonExample = @"<Addons>
    <Addon AddonType=""AddonType.Start"">
        <Dropdown>
            <DropdownToggle Color=""Color.Primary"">Dropdown</DropdownToggle>
            <DropdownMenu>
                <DropdownItem>Action</DropdownItem>
                <DropdownItem>Another action</DropdownItem>
                <DropdownItem>Something else here</DropdownItem>
                <DropdownDivider />
                <DropdownItem>Separated link</DropdownItem>
            </DropdownMenu>
        </Dropdown>
    </Addon>
    <Addon AddonType=""AddonType.Body"">
        <TextEdit />
    </Addon>
</Addons>";

        public const string MultipleAddonsExample = @"<Addons>
    <Addon AddonType=""AddonType.Start"">
        <AddonLabel>Start</AddonLabel>
    </Addon>
    <Addon AddonType=""AddonType.Body"">
        <TextEdit Placeholder=""Placeholder"" />
    </Addon>
    <Addon AddonType=""AddonType.End"">
        <AddonLabel>End</AddonLabel>
    </Addon>
</Addons>";

        public const string StaticAddonExample = @"<Addons>
    <Addon AddonType=""AddonType.Start"">
        <AddonLabel>@@</AddonLabel>
    </Addon>
    <Addon AddonType=""AddonType.Body"">
        <TextEdit Placeholder=""Username"" />
    </Addon>
</Addons>";

        public const string AlertUseProgrammaticallyExample = @"<Alert @ref=""myAlert"" Color=""Color.Success"">
    <AlertMessage>
        Alert test.
    </AlertMessage>
</Alert>

<Button Clicked=""@OnButtonClick"" Color=""Color.Primary"">Show alert</Button>

@code{
    Alert myAlert;

    Task OnButtonClick()
    {
        myAlert.Show();

        return Task.CompletedTask;
    }
}";

        public const string AlertUseWithBindExample = @"<Alert Color=""Color.Success"" @bind-Visible=""@visible"">
    <AlertMessage>
        Alert test.
    </AlertMessage>
</Alert>

<Button Clicked=""@OnButtonClick"" Color=""Color.Primary"">Toggle alert</Button>

@code {
    bool visible = true;

    Task OnButtonClick()
    {
        visible = !visible;

        return Task.CompletedTask;
    }
}";

        public const string AlertWithContentExample = @"<Alert Color=""Color.Info"" @bind-Visible=""@visible"">
    <Heading Size=""HeadingSize.Is4"" TextColor=""TextColor.Success"">
        Big one!
        <CloseButton />
    </Heading>
    <Paragraph>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum.
    </Paragraph>
    <Paragraph>
        <Button Color=""Color.Info"">Wanna do this</Button>
        <Button Color=""Color.Light"">Or do this</Button>
    </Paragraph>
</Alert>
@code {
    bool visible = true;
}";

        public const string BasicAlertExample = @"<Alert Color=""Color.Success"" Visible>
    <AlertMessage>Well done!</AlertMessage>
    <AlertDescription>You successfully read this important alert message.</AlertDescription>
</Alert>";

        public const string CloseAlertExample = @"<Alert Color=""Color.Success"" @bind-Visible=""@visible"">
    <AlertDescription>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    </AlertDescription>
    <AlertMessage>
        Alert Link.
    </AlertMessage>
    <CloseButton />
</Alert>
@code {
    bool visible = true;
}";

        public const string BadgeColorsExample = @"<Badge Color=""Color.Primary"">Primary</Badge>
<Badge Color=""Color.Secondary"">Secondary</Badge>
<Badge Color=""Color.Success"">Success</Badge>
<Badge Color=""Color.Danger"">Danger</Badge>
<Badge Color=""Color.Warning"">Warning</Badge>
<Badge Color=""Color.Info"">Info</Badge>
<Badge Color=""Color.Light"">Light</Badge>
<Badge Color=""Color.Dark"">Dark</Badge>";

        public const string BasicBadgeExample = @"<Badge Color=""Color.Primary"">Hello</Badge>";

        public const string CloseBadgeExample = @"<Badge Color=""Color.Primary"" CloseClicked=""@(()=>Console.WriteLine(""closed""))"">Primary</Badge>";

        public const string TopBarExample = @"<Bar Breakpoint=""Breakpoint.Desktop""
     Background=""Background.Light""
     ThemeContrast=""ThemeContrast.Light"">
    <BarBrand>
        Brandname
    </BarBrand>
    <BarToggler />
    <BarMenu>
        <BarStart>
            <BarItem>
                <BarLink To=""#home"">Home</BarLink>
            </BarItem>
            <BarItem>
                <BarLink To=""#docs"">Documentation</BarLink>
            </BarItem>
            <BarItem>
                <BarDropdown>
                    <BarDropdownToggle>Dropdown</BarDropdownToggle>
                    <BarDropdownMenu>
                        <BarDropdownItem>Action</BarDropdownItem>
                        <BarDropdownDivider />
                        <BarDropdownItem>Another action</BarDropdownItem>
                    </BarDropdownMenu>
                </BarDropdown>
            </BarItem>
        </BarStart>
        <BarEnd>
            <BarItem>
                <Button Color=""Color.Primary"">Sign up</Button>
                <Button Color=""Color.Secondary"">Log in</Button>
            </BarItem>
        </BarEnd>
    </BarMenu>
</Bar>";

        public const string VerticalBarExternalExample = @"<Layout Sider=""true"">
    <LayoutSider>
        <LayoutSiderContent>
            <Bar @ref=""@sidebar"" Mode=""BarMode.VerticalInline""
                 Breakpoint=""Breakpoint.Desktop""
                 Background=""Background.Light""
                 ThemeContrast=""ThemeContrast.Light"">
                <BarItem>Example</BarItem>
            </Bar>
        </LayoutSiderContent>
    </LayoutSider>
    <Layout>
        <LayoutHeader Fixed=""true"">
            <Bar Mode=""BarMode.Horizontal""
                 Background=""Background.Light""
                 ThemeContrast=""ThemeContrast.Light"">
                <BarToggler Bar=""@sidebar"" />
                <BarBrand>
                    <BarItem>
                        <BarLink To=""#"">
                            <BarIcon IconName=""IconName.Dashboard"" />
                            Example
                        </BarLink>
                    </BarItem>
                </BarBrand>
                <BarMenu>
                    <BarItem>Example</BarItem>
                </BarMenu>
                <BarToggler />
            </Bar>
        </LayoutHeader>
    </Layout>
</Layout>

@code {
    private Bar sidebar;
}";

        public const string VerticalBarInlineExample = @"<Bar Mode=""BarMode.VerticalInline""
     Breakpoint=""Breakpoint.Desktop""
     Background=""Background.Light""
     ThemeContrast=""ThemeContrast.Light"">
    <BarToggler />
    <BarBrand>
        <BarItem>
            <BarLink To=""#"">
                <BarIcon IconName=""IconName.Dashboard"" />
                Example
            </BarLink>
        </BarItem>
    </BarBrand>
    <BarMenu>
        <BarItem>Example</BarItem>
    </BarMenu>
</Bar>";

        public const string VerticalBarNestedDropdownsExample = @"<Bar Breakpoint=""Breakpoint.Desktop""
     Background=""Background.Light""
     ThemeContrast=""ThemeContrast.Light"">
    <BarMenu>
        <BarStart>
            <BarItem>
                <BarDropdown>
                    <BarDropdownToggle>
                        Top-level toggler
                    </BarDropdownToggle>
                    <BarDropdownMenu>
                        <BarDropdownItem>
                            Top-level item
                        </BarDropdownItem>
                        <BarDropdown>
                            <BarDropdownToggle>
                                Nested toggler
                            </BarDropdownToggle>
                            <BarDropdownMenu>
                                <BarDropdownItem>
                                    Nested item
                                </BarDropdownItem>
                            </BarDropdownMenu>
                        </BarDropdown>
                    </BarDropdownMenu>
                </BarDropdown>
            </BarItem>
        </BarStart>
    </BarMenu>
</Bar>";

        public const string VerticalBarPopoutExample = @"<Bar Mode=""BarMode.VerticalInline""
     Breakpoint=""Breakpoint.Desktop""
     Background=""Background.Light""
     ThemeContrast=""ThemeContrast.Light"">
    <BarBrand>
        <BarItem>
            <BarLink To=""#"">
                <BarIcon IconName=""IconName.Dashboard"" />
                Blazorise Demo
            </BarLink>
        </BarItem>
    </BarBrand>
    <BarToggler Mode=""BarTogglerMode.Popout"" />
    <BarMenu>
        <BarItem>Popout!</BarItem>
    </BarMenu>
</Bar>";

        public const string VerticalBarRightAlignedExample = @"<Layout Sider=""true"">
    <LayoutSider>
        <LayoutSiderContent>
            <Bar Mode=""BarMode.VerticalInline"" CollapseMode=""BarCollapseMode.Small""
                 Breakpoint=""Breakpoint.Desktop""
                 Background=""Background.Light""
                 ThemeContrast=""ThemeContrast.Light"">
                <BarBrand>
                    <BarItem>
                        <BarLink To=""#"">
                            <BarIcon IconName=""IconName.Dashboard"" />
                            Example
                        </BarLink>
                    </BarItem>
                </BarBrand>
                <BarMenu>
                    <BarStart>
                        <BarItem>
                            <BarDropdown>
                                <BarDropdownToggle>
                                    <BarIcon IconName=""IconName.Edit"" />
                                    Toggle
                                </BarDropdownToggle>
                                <BarDropdownMenu RightAligned=""true"">
                                    <BarDropdownItem>Action</BarDropdownItem>
                                    <BarDropdownItem>Another action</BarDropdownItem>
                                </BarDropdownMenu>
                            </BarDropdown>
                        </BarItem>
                    </BarStart>
                </BarMenu>
            </Bar>
        </LayoutSiderContent>
    </LayoutSider>
</Layout>";

        public const string VerticalBarSideBarExample = @"<Bar Mode=""BarMode.VerticalInline""
     CollapseMode=""BarCollapseMode.Small""
     Breakpoint=""Breakpoint.Desktop""
     NavigationBreakpoint=""Breakpoint.Tablet""
     ThemeContrast=""ThemeContrast.Dark"">
    <BarBrand>
        <BarItem>
            <BarLink To=""#"">
                <BarIcon IconName=""IconName.Dashboard"" />
                Blazorise Demo
            </BarLink>
        </BarItem>
    </BarBrand>
    <BarMenu>
        <BarStart>
            <BarItem>
                <BarLink To=""#home"">
                    <BarIcon IconName=""IconName.Dashboard"" />
                    Home
                </BarLink>
            </BarItem>
            <BarItem>
                <BarLink To=""#docs"">Documentation</BarLink>
            </BarItem>
            <BarItem>
                <BarDropdown>
                    <BarDropdownToggle>
                        <BarIcon IconName=""IconName.Edit"" />
                        Dropdown
                    </BarDropdownToggle>
                    <BarDropdownMenu>
                        <BarDropdownItem>Action</BarDropdownItem>
                        <BarDropdownItem>Another action</BarDropdownItem>
                    </BarDropdownMenu>
                </BarDropdown>
            </BarItem>
        </BarStart>
    </BarMenu>
</Bar>";

        public const string BreadcrumbAutoExample = @"<Breadcrumb Mode=""BreadcrumbMode.Auto"">
    <BreadcrumbItem>
        <BreadcrumbLink To="""">Home</BreadcrumbLink>
    </BreadcrumbItem>
    <BreadcrumbItem>
        <BreadcrumbLink To=""account"">Account</BreadcrumbLink>
    </BreadcrumbItem>
    <BreadcrumbItem>
        <BreadcrumbLink To=""account/settings"">Settings</BreadcrumbLink>
    </BreadcrumbItem>
</Breadcrumb>";

        public const string BreadcrumbManualExample = @"<Breadcrumb>
    <BreadcrumbItem>
        <BreadcrumbLink To=""#"">Home</BreadcrumbLink>
    </BreadcrumbItem>
    <BreadcrumbItem>
        <BreadcrumbLink To=""#"">Library</BreadcrumbLink>
    </BreadcrumbItem>
    <BreadcrumbItem Active=""true"">
        <BreadcrumbLink To=""#"">Data</BreadcrumbLink>
    </BreadcrumbItem>
</Breadcrumb>";

        public const string ActiveButtonExample = @"<Button Color=""Color.Primary"" Active>Primary</Button>
<Button Color=""Color.Secondary"" Active>Secondary</Button>";

        public const string BlockButtonExample = @"<Button Color=""Color.Primary"" Block>Blocked primary</Button>
<Button Color=""Color.Secondary"" Block>Blocked secondary</Button>";

        public const string ButtonExample = @"<Button Color=""Color.Primary"">Click me</Button>";

        public const string ButtonGroupExample = @"<Buttons>
    <Button Color=""Color.Secondary"">LEFT</Button>
    <Button Color=""Color.Secondary"">CENTER</Button>
    <Button Color=""Color.Secondary"">RIGHT</Button>
</Buttons>";

        public const string ButtonUsageExample = @"<Button Color=""Color.Primary"" Clicked=""@OnButtonClicked"">Click me</Button>
@code{
    [Inject] INotificationService NotificationService { get; set; }

    Task OnButtonClicked()
    {
        return NotificationService.Info( ""Hello world!"" );
    }
}";

        public const string ColorButtonsExample = @"<Button Color=""Color.Primary"">Primary</Button>
<Button Color=""Color.Secondary"">Secondary</Button>
<Button Color=""Color.Success"">Success</Button>
<Button Color=""Color.Warning"">Warning</Button>
<Button Color=""Color.Danger"">Danger</Button>
<Button Color=""Color.Info"">Info</Button>
<Button Color=""Color.Light"">Light</Button>
<Button Color=""Color.Dark"">Dark</Button>
<Button>None</Button>";

        public const string DisabledButtonExample = @"<Button Color=""Color.Primary"" Disabled>Primary</Button>
<Button Color=""Color.Secondary"" Disabled>Secondary</Button>";

        public const string LinkButtonExample = @"<Button Color=""Color.Primary"" Type=""ButtonType.Link"" To=""#"">Primary link</Button>
<Button Color=""Color.Secondary"" Type=""ButtonType.Link"" To=""#"" Target=""Target.Blank"">Secondary link</Button>";

        public const string LoadingButtonExample = @"<Button Color=""Color.Primary"" Loading>Primary</Button>
<Button Color=""Color.Primary"" Clicked=""@ShowLoading"" Loading=""@isLoading"">
    <LoadingTemplate>
        This is a custom loading template
    </LoadingTemplate>
    <ChildContent>
        Click to load
    </ChildContent>
</Button>
@code{
    private bool isLoading;

    private async Task ShowLoading()
    {
        isLoading = true;

        await Task.Delay( TimeSpan.FromSeconds( 3 ) );

        isLoading = false;
    }
}";

        public const string OutlineButtonExample = @"<Button Color=""Color.Primary"" Outline>Primary</Button>
<Button Color=""Color.Secondary"" Outline>Secondary</Button>
<Button Color=""Color.Success"" Outline>Success</Button>
<Button Color=""Color.Warning"" Outline>Warning</Button>
<Button Color=""Color.Danger"" Outline>Danger</Button>
<Button Color=""Color.Info"" Outline>Info</Button>
<Button Color=""Color.Light"" Outline>Light</Button>
<Button Color=""Color.Dark"" Outline>Dark</Button>
<Button Outline>None</Button>";

        public const string SubmitButtonExample = @"<Form>
    <Field Horizontal>
        <FieldLabel ColumnSize=""ColumnSize.Is2"">Name</FieldLabel>
        <FieldBody ColumnSize=""ColumnSize.Is10"">
            <TextEdit Placeholder=""Some text value..."" />
        </FieldBody>
    </Field>
    <Field>
        <Button Color=""Color.Primary"" Type=""ButtonType.Submit"" PreventDefaultOnSubmit=""true"">Submit</Button>
    </Field>
</Form>";

        public const string ToolbarButtonsExample = @"<Buttons Role=""ButtonsRole.Toolbar"">
    <Buttons Margin=""Margin.Is2.FromRight"">
        <Button Color=""Color.Primary"">Primary</Button>
        <Button Color=""Color.Secondary"">Secondary</Button>
        <Button Color=""Color.Info"">Info</Button>
    </Buttons>
    <Buttons>
        <Button Color=""Color.Danger"">Danger</Button>
        <Button Color=""Color.Warning"">Warning</Button>
    </Buttons>
    <Buttons Margin=""Margin.Is2.OnX"">
        <Button Color=""Color.Success"">Success</Button>
    </Buttons>
</Buttons>";

        public const string CardDeckExample = @"<CardDeck>
    <Card>
        <CardImage Source=""/img/gallery/2.jpg"" Alt=""Card image cap 3""></CardImage>
        <CardBody>
            <CardTitle Size=""5"">Card title 1</CardTitle>
            <CardText>
                This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.
            </CardText>
            <Button Color=""Color.Primary"">Button</Button>
        </CardBody>
    </Card>
    <Card>
        <CardImage Source=""/img/gallery/3.jpg"" Alt=""Card image cap 9""></CardImage>
        <CardBody>
            <CardTitle Size=""5"">Card title 2</CardTitle>
            <CardText>
                This card has supporting text below as a natural lead-in to additional content.
            </CardText>
            <Button Color=""Color.Primary"">Button</Button>
        </CardBody>
    </Card>
    <Card>
        <CardImage Source=""/img/gallery/4.jpg"" Alt=""Card image cap 12""></CardImage>
        <CardBody>
            <CardTitle Size=""5"">Card title 3</CardTitle>
            <CardText>
                This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.
            </CardText>
            <Button Color=""Color.Primary"">Button</Button>
        </CardBody>
    </Card>
</CardDeck>";

        public const string CardExample = @"<Card Margin=""Margin.Is4.OnY"">
    <CardImage Source=""img/gallery/7.jpg"" Alt=""Placeholder image"">
    </CardImage>
    <CardBody>
        <CardTitle Size=""5"">Card title</CardTitle>
        <CardText>
            Some quick example text to build on the card title and make up the bulk of the card's content.
        </CardText>
        <Button Color=""Color.Primary"">Button</Button>
    </CardBody>
</Card>";

        public const string CarouselExample = @"<Carousel @bind-SelectedSlide=""@selectedSlide"">
    <CarouselSlide Name=""1"">
        <Image Source=""img/gallery/1.jpg"" Text=""Lights"" Display=""Display.Block"" Width=""Width.Is100"" />
    </CarouselSlide>
    <CarouselSlide Name=""2"">
        <Image Source=""img/gallery/2.jpg"" Text=""Keyboard"" Display=""Display.Block"" Width=""Width.Is100"" />
    </CarouselSlide>
    <CarouselSlide Name=""3"">
        <Image Source=""img/gallery/3.jpg"" Text=""Road"" Display=""Display.Block"" Width=""Width.Is100"" />
    </CarouselSlide>
</Carousel>
@code{
    private string selectedSlide = ""2"";
}";

        public const string CheckExample = @"<Check TValue=""bool"">Check me out</Check>";

        public const string CheckWithBindExample = @"<Check TValue=""bool"" @bind-Checked=""@rememberMe"">Remember Me</Check>

@code{
    bool rememberMe;
}";

        public const string CheckWithEventExample = @"<Check TValue=""bool"" Checked=""@rememberMe"" CheckedChanged=""@OnRememberMeChanged"">Remember Me</Check>

@code{
    bool rememberMe;

    void OnRememberMeChanged( bool value )
    {
        rememberMe = value;
    }
}";

        public const string AutoCloseExample = @"<Alert @bind-Visible=""@visible"">
    I can be closed!
    <CloseButton AutoClose=""true"" />
</Alert>
@code {
    bool visible = true;
}";

        public const string ManualCloseExample = @"<Alert Visible=""@visible"">
    I can be closed!
    <CloseButton Clicked=""@OnClicked"" />
</Alert>
@code {
    bool visible = true;

    Task OnClicked()
    {
        visible = false;

        return Task.CompletedTask;
    }
}";

        public const string WithOtherComponentsExample = @"@if ( visible )
{
    <Div>
        Now you see me...
        <CloseButton Clicked=""@OnClicked"" />
    </Div>
}
@code {
    bool visible = true;

    Task OnClicked()
    {
        visible = false;

        return Task.CompletedTask;
    }
}";

        public const string BasicColorExample = @"<ColorEdit Color=""#ff0000"" />";

        public const string BasicDateEditExample = @"<DateEdit TValue=""DateTime?"" />";

        public const string BasicDatePickerExample = @"<DatePicker TValue=""DateTime?"" />";

        public const string DateEditDateTimeExample = @"<DateEdit TValue=""DateTime?"" InputMode=""DateInputMode.DateTime"" />";

        public const string DateEditWithBindExample = @"<DateEdit TValue=""DateTime?"" @bind-Date=""@selectedDate"" />

@code{
    DateTime? selectedDate;
}";

        public const string DateEditWithEventExample = @"<DateEdit TValue=""DateTime?"" Date=""@selectedDate"" DateChanged=""@OnDateChanged"" />

@code{
    DateTime? selectedDate;

    void OnDateChanged( DateTime? date )
    {
        selectedDate = date;
    }
}";

        public const string DatePickerWithIconExample = @"<Addons>
    <Addon AddonType=""AddonType.Body"">
        <DatePicker @ref=""@datePicker"" TValue=""DateTime?"" />
    </Addon>
    <Addon AddonType=""AddonType.End"">
        <Button Color=""Color.Light"" Clicked=""@(()=>datePicker.ToggleAsync())"">
            <Icon Name=""IconName.CalendarDay"" />
        </Button>
    </Addon>
</Addons>
@code{
    DatePicker<DateTime?> datePicker;
}";

        public const string DashedDividerExample = @"<Divider DividerType=""DividerType.Dashed"" />";

        public const string DottedDividerExample = @"<Divider DividerType=""DividerType.Dotted"" />";

        public const string SolidDividerExample = @"<Divider />";

        public const string TextContentDividerExample = @"<Divider DividerType=""DividerType.TextContent"" Text=""Hello Blazorise"" />";

        public const string DropdownExample = @"<Dropdown>
    <DropdownToggle Color=""Color.Primary"">
        Dropdown
    </DropdownToggle>
    <DropdownMenu>
        <DropdownItem>Action</DropdownItem>
        <DropdownDivider />
        <DropdownItem>Another Action</DropdownItem>
    </DropdownMenu>
</Dropdown>";

        public const string ShowMenuExample = @"<Dropdown @ref=""dropdown"" Display=""Display.InlineBlock"">
    <DropdownToggle Color=""Color.Primary"">Menu</DropdownToggle>
    <DropdownMenu>
        <DropdownItem>Action</DropdownItem>
        <DropdownDivider />
        <DropdownItem>Another Action</DropdownItem>
    </DropdownMenu>
</Dropdown>

<Button Clicked=""@ShowMenu"" Color=""Color.Secondary"">Show Menu</Button>
@code {
    Dropdown dropdown;

    Task ShowMenu()
    {
        dropdown.Show();

        return Task.CompletedTask;
    }
}";

        public const string SplitDropdownExample = @"<Dropdown>
    <Button Color=""Color.Primary"">Split Dropdown</Button>
    <DropdownToggle Color=""Color.Primary"" Split=""true"" />
    <DropdownMenu>
        <DropdownItem>Action</DropdownItem>
        <DropdownDivider />
        <DropdownItem>Another Action</DropdownItem>
    </DropdownMenu>
</Dropdown>";

        public const string BasicFieldExample = @"<Field>
    <TextEdit Placeholder=""Name"" />
</Field>";

        public const string BasicFieldsExample = @"<Fields>
    <Field ColumnSize=""ColumnSize.Is6.OnDesktop"">
        <FieldLabel>City</FieldLabel>
        <TextEdit />
    </Field>
    <Field ColumnSize=""ColumnSize.Is4.OnDesktop"">
        <FieldLabel>State</FieldLabel>
        <Select TValue=""string"">
        </Select>
    </Field>
    <Field ColumnSize=""ColumnSize.Is2.OnDesktop"">
        <FieldLabel>Zip</FieldLabel>
        <TextEdit />
    </Field>
</Fields>";

        public const string FieldHiddenExample = @"<Field Visibility=""Visibility.Invisible"">
    <TextEdit />
</Field>";

        public const string FieldWithHelpExample = @"<Field>
    <FieldLabel>Email address</FieldLabel>
    <TextEdit Placeholder=""Enter email"">
        <FieldHelp>Please enter a valid email address</FieldHelp>
    </TextEdit>
</Field>";

        public const string FieldWithLabelExample = @"<Field>
    <FieldLabel>Email address</FieldLabel>
    <TextEdit Placeholder=""Enter email"" />
</Field>";

        public const string HorizontalFieldExample = @"<Field Horizontal=""true"">
    <FieldLabel ColumnSize=""ColumnSize.Is2"">Name</FieldLabel>
    <FieldBody ColumnSize=""ColumnSize.Is10"">
        <TextEdit Placeholder=""Some text value..."" />
    </FieldBody>
</Field>";

        public const string FigureExample = @"<Figure Size=""FigureSize.Is256x256"">
    <FigureImage Source=""img/empty-256x256.png"" AlternateText=""empty-256x256"" />
    <FigureCaption>A caption for the above image.</FigureCaption>
</Figure>";

        public const string ExtensionsLimitFileEditExample = @"<!-- Accept all image formats by IANA media type wildcard-->
<FileEdit Filter=""image/*"" />

<!-- Accept specific image formats by IANA type -->
<FileEdit Filter=""image/jpeg, image/png, image/gif"" />

<!-- Accept specific image formats by extension -->
<FileEdit Filter="".jpg, .png, .gif"" />";

        public const string MultipleFileEditExample = @"<FileEdit Changed=""@OnChanged"" Multiple=""true"" />
@code{
    Task OnChanged( FileChangedEventArgs e )
    {
        return Task.CompletedTask;
    }
}";

        public const string OpenReadStreamFileEditExample = @"@using System.IO

<FileEdit Changed=""@OnChanged"" Written=""@OnWritten"" Progressed=""@OnProgressed"" />

@code{
    string fileContent;

    const int OneMb = 1024 * 1024;

    async Task OnChanged( FileChangedEventArgs e )
    {
        try
        {
            var file = e.Files.FirstOrDefault();
            if ( file == null )
            {
                return;
            }

            var buffer = new byte[OneMb];
            using ( var bufferedStream = new BufferedStream( file.OpenReadStream( long.MaxValue ), OneMb ) )
            {
                int readCount = 0;
                int readBytes;
                while ( ( readBytes = await bufferedStream.ReadAsync( buffer, 0, OneMb ) ) > 0 )
                {
                    Console.WriteLine( $""Read:{readCount++} {readBytes / (double)OneMb} MB"" );
                    // Do work on the first 1MB of data
                }
            }
        }
        catch ( Exception exc )
        {
            Console.WriteLine( exc.Message );
        }
        finally
        {
            this.StateHasChanged();
        }
    }

    void OnWritten( FileWrittenEventArgs e )
    {
        Console.WriteLine( $""File: {e.File.Name} Position: {e.Position} Data: {Convert.ToBase64String( e.Data )}"" );
    }

    void OnProgressed( FileProgressedEventArgs e )
    {
        Console.WriteLine( $""File: {e.File.Name} Progress: {e.Percentage}"" );
    }
}";

        public const string ResetFileEditExample = @"<FileEdit @ref=""@fileEdit"" AutoReset=""false"" Changed=""@OnChanged"" />
@code{
    FileEdit fileEdit;

    Task OnChanged( FileChangedEventArgs e )
    {
        return Task.CompletedTask;
    }

    Task OnSomeButtonClick()
    {
        return fileEdit.Reset().AsTask();
    }
}";

        public const string SingleFileEditExample = @"<FileEdit Changed=""@OnChanged"" />
@code{
    Task OnChanged( FileChangedEventArgs e )
    {
        return Task.CompletedTask;
    }
}";

        public const string WriteToStreamFileEditExample = @"@using System.IO

<FileEdit Changed=""@OnChanged"" Written=""@OnWritten"" Progressed=""@OnProgressed"" />

@code{
    string fileContent;

    async Task OnChanged( FileChangedEventArgs e )
    {
        try
        {
            foreach ( var file in e.Files )
            {
                // A stream is going to be the destination stream we're writing to.
                using ( var stream = new MemoryStream() )
                {
                    // Here we're telling the FileEdit where to write the upload result
                    await file.WriteToStreamAsync( stream );

                    // Once we reach this line it means the file is fully uploaded.
                    // In this case we're going to offset to the beginning of file
                    // so we can read it.
                    stream.Seek( 0, SeekOrigin.Begin );

                    // Use the stream reader to read the content of uploaded file,
                    // in this case we can assume it is a textual file.
                    using ( var reader = new StreamReader( stream ) )
                    {
                        fileContent = await reader.ReadToEndAsync();
                    }
                }
            }
        }
        catch ( Exception exc )
        {
            Console.WriteLine( exc.Message );
        }
        finally
        {
            this.StateHasChanged();
        }
    }

    void OnWritten( FileWrittenEventArgs e )
    {
        Console.WriteLine( $""File: {e.File.Name} Position: {e.Position} Data: {Convert.ToBase64String( e.Data )}"" );
    }

    void OnProgressed( FileProgressedEventArgs e )
    {
        Console.WriteLine( $""File: {e.File.Name} Progress: {e.Percentage}"" );
    }
}";

        public const string BasicContainerExample = @"<Container>
    <Alert Color=""Color.Primary"" Visible=""true"">
        Suspendisse vel quam malesuada, aliquet sem sit amet, fringilla elit. Morbi tempor tincidunt tempor. Etiam id turpis viverra, vulputate sapien nec, varius sem. Curabitur ullamcorper fringilla eleifend. In ut eros hendrerit est consequat posuere et at velit.
    </Alert>
</Container>";

        public const string BasicGridExample = @"<Row>
    <Column ColumnSize=""ColumnSize.Is12"">
        <Alert Color=""Color.Primary"" Visible=""true"">
            Is12
        </Alert>
    </Column>
</Row>
<Row>
    <Column ColumnSize=""ColumnSize.Is8"">
        <Alert Color=""Color.Primary"" Visible=""true"">
            Is8
        </Alert>
    </Column>
    <Column ColumnSize=""ColumnSize.Is4"">
        <Alert Color=""Color.Secondary"" Visible=""true"">
            Is4
        </Alert>
    </Column>
</Row>";

        public const string ContainerFluidExample = @"<Container Fluid=""true"">
    <Alert Color=""Color.Primary"" Visible=""true"">
        Suspendisse vel quam malesuada, aliquet sem sit amet, fringilla elit. Morbi tempor tincidunt tempor. Etiam id turpis viverra, vulputate sapien nec, varius sem. Curabitur ullamcorper fringilla eleifend. In ut eros hendrerit est consequat posuere et at velit.
    </Alert>
</Container>";

        public const string GridGutterExample = @"<Row Gutter=""(32, 16)"">
    <Column ColumnSize=""ColumnSize.Is8"">
        <Alert Color=""Color.Primary"" Visible=""true"">
            I have padding
        </Alert>
    </Column>
    <Column ColumnSize=""ColumnSize.Is4"">
        <Alert Color=""Color.Secondary"" Visible=""true"">
            I also have padding
        </Alert>
    </Column>
</Row>";

        public const string GridOffsetExample = @"<Row>
    <Column ColumnSize=""ColumnSize.Is4"">
        <Alert Color=""Color.Primary"" Visible=""true"">
            Is4
        </Alert>
    </Column>
    <Column ColumnSize=""ColumnSize.Is4.WithOffset"">
        <Alert Color=""Color.Primary"" Visible=""true"">
            Is4.WithOffset
        </Alert>
    </Column>
</Row>
<Row>
    <Column ColumnSize=""ColumnSize.Is3.Is3.WithOffset"">
        <Alert Color=""Color.Primary"" Visible=""true"">
            Is3.Is3.WithOffset
        </Alert>
    </Column>
    <Column ColumnSize=""ColumnSize.Is3.Is3.WithOffset"">
        <Alert Color=""Color.Primary"" Visible=""true"">
            Is3.Is3.WithOffset
        </Alert>
    </Column>
</Row>";

        public const string BasicJumbotronExample = @"<Jumbotron Background=""Background.Light"" Margin=""Margin.Is4.FromBottom"">
    <JumbotronTitle Size=""JumbotronTitleSize.Is4"">Hello, world!</JumbotronTitle>
    <JumbotronSubtitle>
        This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.
    </JumbotronSubtitle>
    <Divider></Divider>
    <Paragraph>
        It uses utility classes for typography and spacing to space content out within the larger container.
    </Paragraph>
</Jumbotron>";

        public const string BasicLayoutExample = @"<Layout>
    <LayoutHeader>
        Header
    </LayoutHeader>
    <LayoutContent>
        Content
    </LayoutContent>
    <LayoutFooter>
        Footer
    </LayoutFooter>
</Layout>";

        public const string BasicLayoutStyledExample = @"<Layout TextAlignment=""TextAlignment.Center"" Style=""height: 300px;"">
    <LayoutHeader Style=""background: #7dbcea; color: white; line-height: 60px;"">
        Header
    </LayoutHeader>
    <LayoutContent Style=""background: rgba(16, 142, 233, 1); color: white; line-height: 120px;"">
        Content
    </LayoutContent>
    <LayoutFooter Style=""background: #7dbcea; color: white; line-height: 60px;"">
        Footer
    </LayoutFooter>
</Layout>";

        public const string LayoutWithSiderAndTopHeaderExample = @"<Layout>
    <LayoutHeader Fixed=""true"">
        Header
    </LayoutHeader>
    <Layout Sider=""true"">
        <LayoutSider>
            <LayoutSiderContent>
                Sider
            </LayoutSiderContent>
        </LayoutSider>
        <Layout>
            <LayoutContent>
                Content
            </LayoutContent>
        </Layout>
    </Layout>
</Layout>";

        public const string LayoutWithSiderAndTopHeaderStyledExample = @"<Layout TextAlignment=""TextAlignment.Center"">
    <LayoutHeader Fixed=""true"" Style=""background: #7dbcea; color: white; line-height: 60px; z-index: 10;"">
        Header
    </LayoutHeader>
    <Layout Sider=""true"" Style=""height: 240px;"">
        <LayoutSider Style=""flex: 0 0 100px; width: 100px; max-width: 100px; min-width: 100px; background: #3ba0e9; color: white; line-height: 120px;"">
            <LayoutSiderContent>
                Sider
            </LayoutSiderContent>
        </LayoutSider>
        <Layout>
            <LayoutContent Style=""background: rgba(16, 142, 233, 1); color: white; line-height: 120px;"">
                Content
            </LayoutContent>
        </Layout>
    </Layout>
</Layout>";

        public const string LayoutWithSiderExample = @"<Layout Sider=""true"">
    <LayoutSider>
        <LayoutSiderContent>
            Sider
        </LayoutSiderContent>
    </LayoutSider>
    <Layout>
        <LayoutHeader Fixed=""true"">
            Header
        </LayoutHeader>
        <LayoutContent>
            Content
        </LayoutContent>
    </Layout>
</Layout>";

        public const string LayoutWithSiderStyledExample = @"<Layout Sider=""true"" TextAlignment=""TextAlignment.Center"">
    <LayoutSider Style=""flex: 0 0 100px; width: 100px; max-width: 100px; min-width: 100px; background: #3ba0e9; color: white; line-height: 120px;"">
        <LayoutSiderContent>
            Sider
        </LayoutSiderContent>
    </LayoutSider>
    <Layout Style=""height: 300px;"">
        <LayoutHeader Fixed=""true"" Style=""background: #7dbcea; color: white; line-height: 60px; z-index: 10;"">
            Header
        </LayoutHeader>
        <LayoutContent Style=""background: rgba(16, 142, 233, 1); color: white; line-height: 120px;"">
            Content
        </LayoutContent>
    </Layout>
</Layout>";

        public const string AnchorLinkExample = @"<Link To=""#"">
    Link
</Link>";

        public const string BasicLinkExample = @"<Link To=""docs"">
    Link
</Link>";

        public const string BasicListGroupExample = @"<ListGroup>
    <ListGroupItem>An item</ListGroupItem>
    <ListGroupItem>A second item</ListGroupItem>
    <ListGroupItem>A third item</ListGroupItem>
    <ListGroupItem>A fourth item</ListGroupItem>
    <ListGroupItem Disabled=""true"">A disabled item</ListGroupItem>
</ListGroup>";

        public const string ListGroupBadgesExample = @"<ListGroup Flush>
    <ListGroupItem Flex=""Flex.JustifyContent.Between.AlignItems.Center"">
        A list item
        <Badge Color=""Color.Primary"" Pill=""true"">14</Badge>
    </ListGroupItem>
    <ListGroupItem Flex=""Flex.JustifyContent.Between.AlignItems.Center"">
        A second list item
        <Badge Color=""Color.Primary"" Pill=""true"">2</Badge>
    </ListGroupItem>
    <ListGroupItem Flex=""Flex.JustifyContent.Between.AlignItems.Center"">
        A third list item
        <Badge Color=""Color.Primary"" Pill=""true"">1</Badge>
    </ListGroupItem>
</ListGroup>";

        public const string ListGroupContextualExample = @"<ListGroup>
    <ListGroupItem Color=""Color.None"">None</ListGroupItem>
    <ListGroupItem Color=""Color.Primary"">Primary</ListGroupItem>
    <ListGroupItem Color=""Color.Secondary"">Secondary</ListGroupItem>
    <ListGroupItem Color=""Color.Success"">Success</ListGroupItem>
    <ListGroupItem Color=""Color.Danger"">Danger</ListGroupItem>
    <ListGroupItem Color=""Color.Warning"">Warning</ListGroupItem>
    <ListGroupItem Color=""Color.Info"">Info</ListGroupItem>
    <ListGroupItem Color=""Color.Light"">Light</ListGroupItem>
    <ListGroupItem Color=""Color.Dark"">Dark</ListGroupItem>
</ListGroup>";

        public const string ListGroupContextualSelectableExample = @"<ListGroup Mode=""ListGroupMode.Selectable"">
    <ListGroupItem Name=""none"" Color=""Color.None"">None</ListGroupItem>
    <ListGroupItem Name=""primary"" Color=""Color.Primary"">Primary</ListGroupItem>
    <ListGroupItem Name=""secondary"" Color=""Color.Secondary"">Secondary</ListGroupItem>
    <ListGroupItem Name=""success"" Color=""Color.Success"">Success</ListGroupItem>
    <ListGroupItem Name=""danger"" Color=""Color.Danger"">Danger</ListGroupItem>
    <ListGroupItem Name=""warning"" Color=""Color.Warning"">Warning</ListGroupItem>
    <ListGroupItem Name=""info"" Color=""Color.Info"">Info</ListGroupItem>
    <ListGroupItem Name=""light"" Color=""Color.Light"">Light</ListGroupItem>
    <ListGroupItem Name=""dark"" Color=""Color.Dark"">Dark</ListGroupItem>
</ListGroup>";

        public const string ListGroupCustomContentExample = @"<ListGroup Flush=""true"">
    <ListGroupItem>
        <Div Flex=""Flex.JustifyContent.Between"" Width=""Width.Is100"">
            <Heading Size=""HeadingSize.Is5"" Margin=""Margin.Is1.FromBottom"">List group item heading</Heading>
            <Small>3 days ago</Small>
        </Div>
        <Paragraph Margin=""Margin.Is1.FromBottom"">Some placeholder content in a paragraph.</Paragraph>
        <Small>And some small print.</Small>
    </ListGroupItem>
    <ListGroupItem>
        <Div Flex=""Flex.JustifyContent.Between"" Width=""Width.Is100"">
            <Heading Size=""HeadingSize.Is5"" Margin=""Margin.Is1.FromBottom"">List group item heading</Heading>
            <Small TextColor=""TextColor.Muted"">3 days ago</Small>
        </Div>
        <Paragraph Margin=""Margin.Is1.FromBottom"">Some placeholder content in a paragraph.</Paragraph>
        <Small TextColor=""TextColor.Muted"">And some muted small print.</Small>
    </ListGroupItem>
    <ListGroupItem>
        <Div Flex=""Flex.JustifyContent.Between"" Width=""Width.Is100"">
            <Heading Size=""HeadingSize.Is5"" Margin=""Margin.Is1.FromBottom"">List group item heading</Heading>
            <Small TextColor=""TextColor.Muted"">3 days ago</Small>
        </Div>
        <Paragraph Margin=""Margin.Is1.FromBottom"">Some placeholder content in a paragraph.</Paragraph>
        <Small TextColor=""TextColor.Muted"">And some muted small print.</Small>
    </ListGroupItem>
</ListGroup>";

        public const string ListGroupFlushExample = @"<ListGroup Flush=""true"">
    <ListGroupItem>An item</ListGroupItem>
    <ListGroupItem>A second item</ListGroupItem>
    <ListGroupItem>A third item</ListGroupItem>
    <ListGroupItem>A fourth item</ListGroupItem>
    <ListGroupItem Disabled=""true"">A disabled item</ListGroupItem>
</ListGroup>";

        public const string ListGroupSelectableExample = @"<ListGroup Mode=""ListGroupMode.Selectable"" @bind-SelectedItem=""selectedItem"">
    <ListGroupItem Name=""first"">An item</ListGroupItem>
    <ListGroupItem Name=""second"">A second item</ListGroupItem>
    <ListGroupItem Name=""third"">A third item</ListGroupItem>
    <ListGroupItem Name=""fourth"">A fourth item</ListGroupItem>
    <ListGroupItem Name=""fifth"" Disabled=""true"">A disabled item</ListGroupItem>
</ListGroup>
@code {
    private string selectedItem = ""first"";
}";

        public const string BasicMemoEditExample = @"<MemoEdit Rows=""5"" />";

        public const string MemoEditTextChangedModeExample = @"public void ConfigureServices( IServiceCollection services )
{
  services
    .AddBlazorise( options =>
    {
      options.ChangeTextOnKeyPress = false;
    } );
}";

        public const string MemoEditTextDelayModeExample = @"public void ConfigureServices( IServiceCollection services )
{
  services
    .AddBlazorise( options =>
    {
      options.DelayTextOnKeyPress = true;
      options.DelayTextOnKeyPressInterval = 300;
    } );
}";

        public const string MemoEditWithBindExample = @"<MemoEdit @bind-Text=""@description"" />

@code{
    string description;
}";

        public const string MemoEditWithEventExample = @"<MemoEdit Text=""@description"" TextChanged=""@OnDescriptionChanged"" />

@code{
    string description;

    Task OnDescriptionChanged( string value )
    {
        description = value;

        return Task.CompletedTask;
    }
}";

        public const string BasicModalExample = @"<Button Clicked=""@ShowModal"">Show Modal</Button>

<Modal @ref=""modalRef"">
    <ModalContent Centered=""true"">
        <ModalHeader>
            <ModalTitle>Employee edit</ModalTitle>
            <CloseButton />
        </ModalHeader>
        <ModalBody>
            <Field>
                <FieldLabel>Name</FieldLabel>
                <TextEdit Placeholder=""Enter name..."" />
            </Field>
            <Field>
                <FieldLabel>Surname</FieldLabel>
                <TextEdit Placeholder=""Enter surname..."" />
            </Field>
        </ModalBody>
        <ModalFooter>
            <Button Color=""Color.Secondary"" Clicked=""@HideModal"">Close</Button>
            <Button Color=""Color.Primary"" Clicked=""@HideModal"">Save Changes</Button>
        </ModalFooter>
    </ModalContent>
</Modal>

@code{
    // reference to the modal component
    private Modal modalRef;

    private Task ShowModal()
    {
        modalRef.Show();

        return Task.CompletedTask;
    }

    private Task HideModal()
    {
        modalRef.Hide();

        return Task.CompletedTask;
    }
}";

        public const string ModalClosingExample = @"<Modal @ref=""modalRef"" Closing=""@OnModalClosing"">
    ...
</Modal>

@code{
    // reference to the modal component
    private Modal modalRef;

    private void OnModalClosing( ModalClosingEventArgs e )
    {
        // just set Cancel to true to prevent modal from closing
        e.Cancel = true;
    }
}";

        public const string BasicNumericEditExample = @"<NumericEdit Value=""123"" />";

        public const string NumericEditGenericExample = @"<NumericEdit TValue=""decimal?"" />";

        public const string BasicPaginationExample = @"<Pagination>
    <PaginationItem>
        <PaginationLink>
            <span aria-hidden=""true"">«</span>
        </PaginationLink>
    </PaginationItem>
    <PaginationItem>
        <PaginationLink>
            1
        </PaginationLink>
    </PaginationItem>
    <PaginationItem>
        <PaginationLink>
            2
        </PaginationLink>
    </PaginationItem>
    <PaginationItem>
        <PaginationLink>
            3
        </PaginationLink>
    </PaginationItem>
    <PaginationItem>
        <PaginationLink>
            <span aria-hidden=""true"">»</span>
        </PaginationLink>
    </PaginationItem>
</Pagination>";

        public const string BasicPageProgressExample = @"<PageProgress Visible=""true"" Value=""25"" />";

        public const string BasicProgressExample = @"<Progress Value=""25"" />";

        public const string IndeterminatePageProgressExample = @"<PageProgress Visible=""true"" />";

        public const string MultipleProgressExample = @"<Progress>
    <ProgressBar Value=""15"" />
    <ProgressBar Color=""Color.Success"" Value=""30"" />
    <ProgressBar Color=""Color.Info"" Value=""20"" />
</Progress>";

        public const string BasicRadioGroupExample = @"<RadioGroup TValue=""string"" Name=""colors"">
    <Radio TValue=""string"" Value=""@(""red"")"">Red</Radio>
    <Radio TValue=""string"" Value=""@(""green"")"">Green</Radio>
    <Radio TValue=""string"" Value=""@(""blue"")"">Blue</Radio>
</RadioGroup>";

        public const string RadioGroupButtonsExample = @"<RadioGroup TValue=""string"" Name=""colors"" Buttons=""true"">
    <Radio TValue=""string"" Value=""@(""red"")"">Red</Radio>
    <Radio TValue=""string"" Value=""@(""green"")"">Green</Radio>
    <Radio TValue=""string"" Value=""@(""blue"")"">Blue</Radio>
</RadioGroup>";

        public const string RadioGroupWithBindExample = @"<RadioGroup TValue=""string"" Name=""colors"" @bind-CheckedValue=""@checkedValue"">
    <Radio TValue=""string"" Value=""@(""red"")"">Red</Radio>
    <Radio TValue=""string"" Value=""@(""green"")"">Green</Radio>
    <Radio TValue=""string"" Value=""@(""blue"")"">Blue</Radio>
</RadioGroup>

@code{
    string checkedValue = ""green"";
}";

        public const string RadioGroupWithEventExample = @"<RadioGroup TValue=""string""
            Name=""colors""
            CheckedValue=""@checkedValue""
            CheckedValueChanged=""@OnCheckedValueChanged"">
    <Radio TValue=""string"" Value=""@(""red"")"">Red</Radio>
    <Radio TValue=""string"" Value=""@(""green"")"">Green</Radio>
    <Radio TValue=""string"" Value=""@(""blue"")"">Blue</Radio>
</RadioGroup>

@code{
    string checkedValue = ""green"";

    Task OnCheckedValueChanged( string value )
    {
        checkedValue = value;

        return Task.CompletedTask;
    }
}";

        public const string StandaloneRadioExample = @"<Radio TValue=""string"" Group=""colors"" Value=""@(""red"")"">Red</Radio>
<Radio TValue=""string"" Group=""colors"" Value=""@(""green"")"">Green</Radio>
<Radio TValue=""string"" Group=""colors"" Value=""@(""blue"")"">Blue</Radio>";

        public const string BasicRatingExample = @"<Rating Color=""Color.Primary"" />";

        public const string RatingWithBindExample = @"<Rating Color=""Color.Primary"" @bind-SelectedValue=""@SelectedValue"" MaxValue=""10"" />

@code{
    int SelectedValue = 7;
}";

        public const string BasicRepeaterExample = @"<ul>
    <Repeater Items=""@items"" CollectionChanged=""@OnCollectionChanged"">
        <li style=""@GetColor( context )"">@context</li>
    </Repeater>
</ul>

@code{
    System.Collections.ObjectModel.ObservableCollection<int> items { get; } = new( Enumerable.Range( 1, 4 ) );

    Task OnCollectionChanged( System.Collections.Specialized.NotifyCollectionChangedEventArgs eventArgs )
    {
        // do something

        return Task.CompletedTask;
    }

    private static string GetColor( int number )
    {
        const string letters = ""0123456789ABCDEF"";

        var color = """";

        for ( var i = 0; i < 6; i++ )
        {
            color += letters[( 3 * number + i ) % letters.Length];
        }

        return $""color: #{color}"";
    }
}";

        public const string BasicSelectExample = @"<Select TValue=""int"">
    <SelectItem Value=""1"">One</SelectItem>
    <SelectItem Value=""2"">Two</SelectItem>
    <SelectItem Value=""3"">Three</SelectItem>
    <SelectItem Value=""4"">Four</SelectItem>
</Select>";

        public const string GroupSelectExample = @"<Select TValue=""int"">
    <SelectGroup Label=""Group 1"">
        <SelectItem Value=""1"">One</SelectItem>
        <SelectItem Value=""2"">Two</SelectItem>
    </SelectGroup>
    <SelectGroup Label=""Group 2"">
        <SelectItem Value=""3"">Three</SelectItem>
        <SelectItem Value=""4"">Four</SelectItem>
    </SelectGroup>
</Select>";

        public const string MultipleSelectExample = @"<Select TValue=""int"" Multiple=""true"">
    <SelectItem Value=""1"">One</SelectItem>
    <SelectItem Value=""2"">Two</SelectItem>
    <SelectItem Value=""3"">Three</SelectItem>
    <SelectItem Value=""4"">Four</SelectItem>
</Select>";

        public const string SelectWithBindExample = @"<Select @bind-SelectedValue=""@selectedValue"">
    <SelectItem Value=""1"">One</SelectItem>
    <SelectItem Value=""2"">Two</SelectItem>
    <SelectItem Value=""3"">Three</SelectItem>
    <SelectItem Value=""4"">Four</SelectItem>
</Select>

@code{
    int selectedValue;
}";

        public const string SelectWithEventExample = @"<Select TValue=""int"" SelectedValue=""@selectedValue"" SelectedValueChanged=""@OnSelectedValueChanged"">
    <SelectItem Value=""1"">One</SelectItem>
    <SelectItem Value=""2"">Two</SelectItem>
    <SelectItem Value=""3"">Three</SelectItem>
    <SelectItem Value=""4"">Four</SelectItem>
</Select>

@code{
    int selectedValue;

    Task OnSelectedValueChanged( int value )
    {
        selectedValue = value;
        Console.WriteLine( selectedValue );

        return Task.CompletedTask;
    }
}";

        public const string BasicSliderExample = @"<Slider TValue=""decimal"" Value=""25m"" Max=""100m"" />";

        public const string BasicStepExample = @"<Steps SelectedStep=""@selectedStep"" SelectedStepChanged=""@OnSelectedStepChanged"">
    <Items>
        <Step Name=""step1"">Step 1</Step>
        <Step Name=""step2"">Step 2</Step>
        <Step Name=""step3"">Step 3</Step>
        <Step Name=""step4"">
            <Marker>
                <Icon Name=""IconName.Flag"" />
            </Marker>
            <Caption>
                Finish
            </Caption>
        </Step>
    </Items>
    <Content>
        <StepPanel Name=""step1"">
            Content for step 1.
        </StepPanel>
        <StepPanel Name=""step2"">
            Content for step 2.
        </StepPanel>
        <StepPanel Name=""step3"">
            Content for step 3.
        </StepPanel>
        <StepPanel Name=""step4"">
            Content for finish.
        </StepPanel>
    </Content>
</Steps>
@code{
    string selectedStep = ""step1"";

    private Task OnSelectedStepChanged( string name )
    {
        selectedStep = name;

        return Task.CompletedTask;
    }
}";

        public const string BasicSwitchExample = @"<Switch TValue=""bool"">Remember me</Switch>";

        public const string SwitchWithBindExample = @"<Switch TValue=""bool"" @bind-Checked=""@rememberMe"">Remember Me</Switch>

@code{
    bool rememberMe;
}";

        public const string SwitchWithEventExample = @"<Switch TValue=""bool"" Checked=""@rememberMe"" CheckedChanged=""@OnRememberMeChanged"">Remember Me</Switch>

@code{
    bool rememberMe;

    Task OnRememberMeChanged( bool value )
    {
        rememberMe = value;

        return Task.CompletedTask;
    }
}";

        public const string BasicTableExample = @"<Table>
    <TableHeader>
        <TableRow>
            <TableHeaderCell>#</TableHeaderCell>
            <TableHeaderCell>First Name</TableHeaderCell>
            <TableHeaderCell>Last Name</TableHeaderCell>
            <TableHeaderCell>Username</TableHeaderCell>
        </TableRow>
    </TableHeader>
    <TableBody>
        <TableRow>
            <TableRowHeader>1</TableRowHeader>
            <TableRowCell>Mark</TableRowCell>
            <TableRowCell>Otto</TableRowCell>
            <TableRowCell>@@mdo</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>2</TableRowHeader>
            <TableRowCell>Jacob</TableRowCell>
            <TableRowCell>Thornton</TableRowCell>
            <TableRowCell>@@fat</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>3</TableRowHeader>
            <TableRowCell>Larry</TableRowCell>
            <TableRowCell>the Bird</TableRowCell>
            <TableRowCell>@@twitter</TableRowCell>
        </TableRow>
    </TableBody>
</Table>";

        public const string TableBorderedExample = @"<Table Bordered=""true"">
    <TableHeader>
        <TableRow>
            <TableHeaderCell>#</TableHeaderCell>
            <TableHeaderCell>First Name</TableHeaderCell>
            <TableHeaderCell>Last Name</TableHeaderCell>
            <TableHeaderCell>Username</TableHeaderCell>
        </TableRow>
    </TableHeader>
    <TableBody>
        <TableRow>
            <TableRowHeader>1</TableRowHeader>
            <TableRowCell>Mark</TableRowCell>
            <TableRowCell>Otto</TableRowCell>
            <TableRowCell>@@mdo</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>2</TableRowHeader>
            <TableRowCell>Jacob</TableRowCell>
            <TableRowCell>Thornton</TableRowCell>
            <TableRowCell>@@fat</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>3</TableRowHeader>
            <TableRowCell>Larry</TableRowCell>
            <TableRowCell>the Bird</TableRowCell>
            <TableRowCell>@@twitter</TableRowCell>
        </TableRow>
    </TableBody>
</Table>";

        public const string TableBorderlessExample = @"<Table Borderless=""true"">
    <TableHeader>
        <TableRow>
            <TableHeaderCell>#</TableHeaderCell>
            <TableHeaderCell>First Name</TableHeaderCell>
            <TableHeaderCell>Last Name</TableHeaderCell>
            <TableHeaderCell>Username</TableHeaderCell>
        </TableRow>
    </TableHeader>
    <TableBody>
        <TableRow>
            <TableRowHeader>1</TableRowHeader>
            <TableRowCell>Mark</TableRowCell>
            <TableRowCell>Otto</TableRowCell>
            <TableRowCell>@@mdo</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>2</TableRowHeader>
            <TableRowCell>Jacob</TableRowCell>
            <TableRowCell>Thornton</TableRowCell>
            <TableRowCell>@@fat</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>3</TableRowHeader>
            <TableRowCell>Larry</TableRowCell>
            <TableRowCell>the Bird</TableRowCell>
            <TableRowCell>@@twitter</TableRowCell>
        </TableRow>
    </TableBody>
</Table>";

        public const string TableDarkHeaderExample = @"<Table>
    <TableHeader ThemeContrast=""ThemeContrast.Dark"">
        <TableRow>
            <TableHeaderCell>#</TableHeaderCell>
            <TableHeaderCell>First Name</TableHeaderCell>
            <TableHeaderCell>Last Name</TableHeaderCell>
            <TableHeaderCell>Username</TableHeaderCell>
        </TableRow>
    </TableHeader>
    <TableBody>
        <TableRow>
            <TableRowHeader>1</TableRowHeader>
            <TableRowCell>Mark</TableRowCell>
            <TableRowCell>Otto</TableRowCell>
            <TableRowCell>@@mdo</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>2</TableRowHeader>
            <TableRowCell>Jacob</TableRowCell>
            <TableRowCell>Thornton</TableRowCell>
            <TableRowCell>@@fat</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>3</TableRowHeader>
            <TableRowCell>Larry</TableRowCell>
            <TableRowCell>the Bird</TableRowCell>
            <TableRowCell>@@twitter</TableRowCell>
        </TableRow>
    </TableBody>
</Table>";

        public const string TableFixedHeaderExample = @"<Table FixedHeader=""true"" FixedHeaderTableHeight=""300px"">
    <TableHeader>
        <TableRow>
            <TableHeaderCell>#</TableHeaderCell>
            <TableHeaderCell>First Name</TableHeaderCell>
            <TableHeaderCell>Last Name</TableHeaderCell>
            <TableHeaderCell>Username</TableHeaderCell>
        </TableRow>
    </TableHeader>
    <TableBody>
        <TableRow>
            <TableRowHeader>1</TableRowHeader>
            <TableRowCell>Mark</TableRowCell>
            <TableRowCell>Otto</TableRowCell>
            <TableRowCell>@@mdo</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>2</TableRowHeader>
            <TableRowCell>Jacob</TableRowCell>
            <TableRowCell>Thornton</TableRowCell>
            <TableRowCell>@@fat</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>3</TableRowHeader>
            <TableRowCell>Larry</TableRowCell>
            <TableRowCell>the Bird</TableRowCell>
            <TableRowCell>@@twitter</TableRowCell>
        </TableRow>
    </TableBody>
</Table>";

        public const string TableHoverableExample = @"<Table Hoverable=""true"">
    <TableHeader>
        <TableRow>
            <TableHeaderCell>#</TableHeaderCell>
            <TableHeaderCell>First Name</TableHeaderCell>
            <TableHeaderCell>Last Name</TableHeaderCell>
            <TableHeaderCell>Username</TableHeaderCell>
        </TableRow>
    </TableHeader>
    <TableBody>
        <TableRow>
            <TableRowHeader>1</TableRowHeader>
            <TableRowCell>Mark</TableRowCell>
            <TableRowCell>Otto</TableRowCell>
            <TableRowCell>@@mdo</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>2</TableRowHeader>
            <TableRowCell>Jacob</TableRowCell>
            <TableRowCell>Thornton</TableRowCell>
            <TableRowCell>@@fat</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>3</TableRowHeader>
            <TableRowCell>Larry</TableRowCell>
            <TableRowCell>the Bird</TableRowCell>
            <TableRowCell>@@twitter</TableRowCell>
        </TableRow>
    </TableBody>
</Table>";

        public const string TableLightHeaderExample = @"<Table>
    <TableHeader ThemeContrast=""ThemeContrast.Light"">
        <TableRow>
            <TableHeaderCell>#</TableHeaderCell>
            <TableHeaderCell>First Name</TableHeaderCell>
            <TableHeaderCell>Last Name</TableHeaderCell>
            <TableHeaderCell>Username</TableHeaderCell>
        </TableRow>
    </TableHeader>
    <TableBody>
        <TableRow>
            <TableRowHeader>1</TableRowHeader>
            <TableRowCell>Mark</TableRowCell>
            <TableRowCell>Otto</TableRowCell>
            <TableRowCell>@@mdo</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>2</TableRowHeader>
            <TableRowCell>Jacob</TableRowCell>
            <TableRowCell>Thornton</TableRowCell>
            <TableRowCell>@@fat</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>3</TableRowHeader>
            <TableRowCell>Larry</TableRowCell>
            <TableRowCell>the Bird</TableRowCell>
            <TableRowCell>@@twitter</TableRowCell>
        </TableRow>
    </TableBody>
</Table>";

        public const string TableNarrowExample = @"<Table Narrow=""true"">
    <TableHeader>
        <TableRow>
            <TableHeaderCell>#</TableHeaderCell>
            <TableHeaderCell>First Name</TableHeaderCell>
            <TableHeaderCell>Last Name</TableHeaderCell>
            <TableHeaderCell>Username</TableHeaderCell>
        </TableRow>
    </TableHeader>
    <TableBody>
        <TableRow>
            <TableRowHeader>1</TableRowHeader>
            <TableRowCell>Mark</TableRowCell>
            <TableRowCell>Otto</TableRowCell>
            <TableRowCell>@@mdo</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>2</TableRowHeader>
            <TableRowCell>Jacob</TableRowCell>
            <TableRowCell>Thornton</TableRowCell>
            <TableRowCell>@@fat</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>3</TableRowHeader>
            <TableRowCell>Larry</TableRowCell>
            <TableRowCell>the Bird</TableRowCell>
            <TableRowCell>@@twitter</TableRowCell>
        </TableRow>
    </TableBody>
</Table>";

        public const string TableScrollToExample = @"<Table @ref=""@tableRef"" FixedHeader=""true"" FixedHeaderTableHeight=""300px"">
    <TableHeader>
        <TableRow>
            <TableHeaderCell>#</TableHeaderCell>
            <TableHeaderCell>First Name</TableHeaderCell>
            <TableHeaderCell>Last Name</TableHeaderCell>
            <TableHeaderCell>Username</TableHeaderCell>
        </TableRow>
    </TableHeader>
    <TableBody>
        <TableRow>
            <TableRowHeader>1</TableRowHeader>
            <TableRowCell>Mark</TableRowCell>
            <TableRowCell>Otto</TableRowCell>
            <TableRowCell>@@mdo</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>2</TableRowHeader>
            <TableRowCell>Jacob</TableRowCell>
            <TableRowCell>Thornton</TableRowCell>
            <TableRowCell>@@fat</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>3</TableRowHeader>
            <TableRowCell>Larry</TableRowCell>
            <TableRowCell>the Bird</TableRowCell>
            <TableRowCell>@@twitter</TableRowCell>
        </TableRow>
    </TableBody>
</Table>
@code{
    Table tableRef;

    private Task ScrollToRow()
        => tableRef.ScrollToRow( 1 ).AsTask();

    private Task ScrollToPixels()
        => tableRef.ScrollToPixels( 250 ).AsTask();
}";

        public const string TableStrippedExample = @"<Table Striped=""true"">
    <TableHeader>
        <TableRow>
            <TableHeaderCell>#</TableHeaderCell>
            <TableHeaderCell>First Name</TableHeaderCell>
            <TableHeaderCell>Last Name</TableHeaderCell>
            <TableHeaderCell>Username</TableHeaderCell>
        </TableRow>
    </TableHeader>
    <TableBody>
        <TableRow>
            <TableRowHeader>1</TableRowHeader>
            <TableRowCell>Mark</TableRowCell>
            <TableRowCell>Otto</TableRowCell>
            <TableRowCell>@@mdo</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>2</TableRowHeader>
            <TableRowCell>Jacob</TableRowCell>
            <TableRowCell>Thornton</TableRowCell>
            <TableRowCell>@@fat</TableRowCell>
        </TableRow>
        <TableRow>
            <TableRowHeader>3</TableRowHeader>
            <TableRowCell>Larry</TableRowCell>
            <TableRowCell>the Bird</TableRowCell>
            <TableRowCell>@@twitter</TableRowCell>
        </TableRow>
    </TableBody>
</Table>";

        public const string BasicTabExample = @"<Tabs SelectedTab=""@selectedTab"" SelectedTabChanged=""@OnSelectedTabChanged"">
    <Items>
        <Tab Name=""home"">Home</Tab>
        <Tab Name=""profile"">Profile</Tab>
        <Tab Name=""messages"">Messages</Tab>
        <Tab Name=""settings"">Settings</Tab>
    </Items>
    <Content>
        <TabPanel Name=""home"">
            Content for home.
        </TabPanel>
        <TabPanel Name=""profile"">
            Content for profile.
        </TabPanel>
        <TabPanel Name=""messages"">
            Content for messages.
        </TabPanel>
        <TabPanel Name=""settings"">
            Content for settings.
        </TabPanel>
    </Content>
</Tabs>
@code{
    string selectedTab = ""profile"";

    private Task OnSelectedTabChanged( string name )
    {
        selectedTab = name;

        return Task.CompletedTask;
    }
}";

        public const string BasicTextEditExample = @"<TextEdit />";

        public const string TextEditDisabledExample = @"<TextEdit Disabled />";

        public const string TextEditMaskExample = @"<TextEdit MaskType=""MaskType.RegEx"" EditMask=""^[a-zA-Z ]*$"" />";

        public const string TextEditPatternExample = @"<Validation UsePattern=""true"">
    <TextEdit Pattern=""[A-Za-z]{3}"">
        <Feedback>
            <ValidationError>Pattern does not match!</ValidationError>
        </Feedback>
    </TextEdit>
</Validation>";

        public const string TextEditPlaceholderExample = @"<TextEdit Placeholder=""Some text value..."" />";

        public const string TextEditPlaintextExample = @"<TextEdit Plaintext />";

        public const string TextEditReadonlyExample = @"<TextEdit ReadOnly />";

        public const string TextEditRoleExample = @"<TextEdit Role=""TextRole.Email"" />
<TextEdit Role=""TextRole.Password"" />";

        public const string TextEditSizingExample = @"<TextEdit Size=""Size.Small"" />
<TextEdit Size=""Size.Large"" />";

        public const string TextEditTextChangedModeExample = @"public void ConfigureServices( IServiceCollection services )
{
  services
    .AddBlazorise( options =>
    {
      options.ChangeTextOnKeyPress = false;
    } );
}";

        public const string TextEditTextDelayModeExample = @"public void ConfigureServices( IServiceCollection services )
{
  services
    .AddBlazorise( options =>
    {
      options.DelayTextOnKeyPress = true;
      options.DelayTextOnKeyPressInterval = 300;
    } );
}";

        public const string TextEditWithBindExample = @"<TextEdit @bind-Text=""@name"" />

@code{
    string name;
}";

        public const string TextEditWithEventExample = @"<TextEdit Text=""@name"" TextChanged=""@OnNameChanged"" />

@code{
    string name;

    Task OnNameChanged( string value )
    {
        name = value;

        return Task.CompletedTask;
    }
}";

        public const string ThemingColorsExample = @"<Blazorise.ThemeProvider Theme=""@theme"">
    <Router AppAssembly=""typeof(App).Assembly"" />
</Blazorise.ThemeProvider>

@code{
    private Theme theme = new Theme
    {
        ColorOptions = new ThemeColorOptions
        {
            Primary = ""#45B1E8"",
            Secondary = ""#A65529"",
            // other
        }
    };
}";

        public const string ThemingGradientExample = @"<Blazorise.ThemeProvider Theme=""@theme"">
    <Router AppAssembly=""typeof(App).Assembly"" />
</Blazorise.ThemeProvider>

@code{
    private Theme theme = new Theme
    {
        IsGradient = true,
    };
}";

        public const string ThemingRoundedExample = @"<Blazorise.ThemeProvider Theme=""@theme"">
    <Router AppAssembly=""typeof(App).Assembly"" />
</Blazorise.ThemeProvider>

@code{
    private Theme theme = new Theme
    {
        IsRounded = false,
    };
}";

        public const string ThemingRuntimeExample = @"<Button Clicked=""@(()=>OnThemeColorChanged(""#d16f9e""))"">Change theme</Button>

@code{
    Task OnThemeColorChanged( string value )
    {
        if ( Theme?.ColorOptions != null )
            Theme.ColorOptions.Primary = value;

        if ( Theme?.BackgroundOptions != null )
            Theme.BackgroundOptions.Primary = value;

        Theme.ThemeHasChanged();

        return Task.CompletedTask;
    }

    [CascadingParameter] Theme Theme { get; set; }
}";

        public const string ThemingStartExample = @"<Blazorise.ThemeProvider Theme=""@theme"">
    <Router AppAssembly=""typeof(App).Assembly"" />
</Blazorise.ThemeProvider>

@code{
    private Theme theme = new Theme
    {
        // theme settings
    };
}";

        public const string BasicTimeEditExample = @"<TimeEdit TValue=""TimeSpan?"" />";

        public const string BasicTimePickerExample = @"<TimePicker TValue=""TimeSpan?"" />";

        public const string TimeEditWithBindExample = @"<TimeEdit TValue=""TimeSpan?"" @bind-Time=""@selectedTime"" />

@code{
    TimeSpan? selectedTime;
}";

        public const string TimeEditWithEventExample = @"<TimeEdit TValue=""TimeSpan?"" Time=""@selectedTime"" TimeChanged=""@OnTimeChanged"" />

@code{
    TimeSpan? selectedTime;

    Task OnTimeChanged( TimeSpan? Time )
    {
        selectedTime = Time;

        return Task.CompletedTask;
    }
}";

        public const string TimePickerWithIconExample = @"<Addons>
    <Addon AddonType=""AddonType.Body"">
        <TimePicker @ref=""@timePicker"" TValue=""TimeSpan?"" />
    </Addon>
    <Addon AddonType=""AddonType.End"">
        <Button Color=""Color.Light"" Clicked=""@(()=>timePicker.ToggleAsync())"">
            <Icon Name=""IconName.CalendarDay"" />
        </Button>
    </Addon>
</Addons>
@code{
    TimePicker<TimeSpan?> timePicker;
}";

        public const string BasicTooltipExample = @"<Tooltip Text=""Hello tooltip"">
    <Button Color=""Color.Primary"">Hover me</Button>
</Tooltip>";

        public const string TooltipPositionsExample = @"<Tooltip Text=""Hello tooltip"" Placement=""TooltipPlacement.Top"">
    <Button Color=""Color.Primary"">Top tooltip</Button>
</Tooltip>
<Tooltip Text=""Hello tooltip"" Placement=""TooltipPlacement.Right"">
    <Button Color=""Color.Primary"">Right tooltip</Button>
</Tooltip>
<Tooltip Text=""Hello tooltip"" Placement=""TooltipPlacement.Left"">
    <Button Color=""Color.Primary"">Left tooltip</Button>
</Tooltip>
<Tooltip Text=""Hello tooltip"" Placement=""TooltipPlacement.Bottom"">
    <Button Color=""Color.Primary"">Bottom tooltip</Button>
</Tooltip>";

        public const string TypographyDisplayHeadingExample = @"<DisplayHeading Size=""DisplayHeadingSize.Is1"">Display 1</DisplayHeading>
<DisplayHeading Size=""DisplayHeadingSize.Is2"">Display 2</DisplayHeading>
<DisplayHeading Size=""DisplayHeadingSize.Is3"">Display 3</DisplayHeading>
<DisplayHeading Size=""DisplayHeadingSize.Is4"">Display 4</DisplayHeading>";

        public const string TypographyHeadingExample = @"<Heading Size=""HeadingSize.Is1"">h1. Blazorise heading</Heading>
<Heading Size=""HeadingSize.Is2"">h2. Blazorise heading</Heading>
<Heading Size=""HeadingSize.Is3"">h3. Blazorise heading</Heading>
<Heading Size=""HeadingSize.Is4"">h4. Blazorise heading</Heading>
<Heading Size=""HeadingSize.Is5"">h5. Blazorise heading</Heading>
<Heading Size=""HeadingSize.Is6"">h6. Blazorise heading</Heading>";

        public const string TypographyParagraphExample = @"<Paragraph>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cras fermentum odio eu feugiat pretium nibh ipsum consequat. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Nunc sed velit dignissim sodales ut. Mi bibendum neque egestas congue quisque egestas diam in arcu. Quis vel eros donec ac odio tempor. Fermentum posuere urna nec tincidunt praesent. Eget velit aliquet sagittis id consectetur. Molestie at elementum eu facilisis sed odio morbi quis commodo. Ut consequat semper viverra nam libero justo laoreet sit.
</Paragraph>
<Paragraph>
    Cursus euismod quis viverra nibh cras. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Varius quam quisque id diam vel quam. Eget sit amet tellus cras adipiscing enim eu turpis. In est ante in nibh mauris cursus mattis. Interdum velit laoreet id donec ultrices tincidunt. Sollicitudin aliquam ultrices sagittis orci a. Turpis egestas sed tempus urna et pharetra pharetra. Felis bibendum ut tristique et egestas quis ipsum suspendisse. Ipsum dolor sit amet consectetur adipiscing elit ut. Enim eu turpis egestas pretium aenean pharetra. Diam sit amet nisl suscipit adipiscing bibendum est. Turpis massa sed elementum tempus egestas. Accumsan in nisl nisi scelerisque eu ultrices vitae. Purus ut faucibus pulvinar elementum integer. Id interdum velit laoreet id donec ultrices tincidunt arcu. Aliquam vestibulum morbi blandit cursus risus at ultrices.
</Paragraph>";

        public const string TypographyTextExample = @"<Text TextColor=""TextColor.Primary"">
    Lorem ipsum dolor sit amet.
</Text>
<Text TextColor=""TextColor.Secondary"">
    Cursus euismod quis viverra nibh cras.
</Text>";

        public const string AsyncValidationExample = @"@using System.Threading

<Validation AsyncValidator=""@ValidateNameAsync"">
    <TextEdit Placeholder=""Enter name"">
        <Feedback>
            <ValidationError>Enter valid name!</ValidationError>
        </Feedback>
    </TextEdit>
</Validation>
@code{
    Random random = new Random();

    async Task ValidateNameAsync( ValidatorEventArgs e, CancellationToken cancellationToken )
    {
        cancellationToken.ThrowIfCancellationRequested();

        // some long running task or call to the rest API
        await Task.Delay( random.Next( 600 ) );

        e.Status = string.IsNullOrEmpty( Convert.ToString( e.Value ) )
            ? ValidationStatus.Error
            : ValidationStatus.Success;
    }
}";

        public const string AutoValidationExample = @"<Validations Mode=""ValidationMode.Auto"" ValidateOnLoad=""true"">
    ...
</Validations>";

        public const string BasicValidationExample = @"<Validation Validator=""@ValidateEmail"">
    <TextEdit Placeholder=""Enter email"">
        <Feedback>
            <ValidationNone>Please enter the email.</ValidationNone>
            <ValidationSuccess>Email is good.</ValidationSuccess>
            <ValidationError>Enter valid email!</ValidationError>
        </Feedback>
    </TextEdit>
</Validation>
@code{
    void ValidateEmail( ValidatorEventArgs e )
    {
        var email = Convert.ToString( e.Value );

        e.Status = string.IsNullOrEmpty( email ) ? ValidationStatus.None :
            email.Contains( ""@"" ) ? ValidationStatus.Success : ValidationStatus.Error;
    }
}";

        public const string DataAnnotationValidationExample = @"@using System.ComponentModel.DataAnnotations

<Validations Mode=""ValidationMode.Auto"" Model=""@user"">
    <Validation>
        <Field Horizontal=""true"">
            <FieldLabel ColumnSize=""ColumnSize.Is2"">Full Name</FieldLabel>
            <FieldBody ColumnSize=""ColumnSize.Is10"">
                <TextEdit Placeholder=""First and last name"" @bind-Text=""@user.Name"">
                    <Feedback>
                        <ValidationError />
                    </Feedback>
                </TextEdit>
            </FieldBody>
        </Field>
    </Validation>
    <Validation>
        <Field Horizontal=""true"">
            <FieldLabel ColumnSize=""ColumnSize.Is2"">Email</FieldLabel>
            <FieldBody ColumnSize=""ColumnSize.Is10"">
                <TextEdit Placeholder=""Enter email"" @bind-Text=""@user.Email"">
                    <Feedback>
                        <ValidationError />
                    </Feedback>
                </TextEdit>
            </FieldBody>
        </Field>
    </Validation>
    <Validation>
        <Field Horizontal=""true"">
            <FieldLabel ColumnSize=""ColumnSize.Is2"">Password</FieldLabel>
            <FieldBody ColumnSize=""ColumnSize.Is10"">
                <TextEdit Role=""TextRole.Password"" Placeholder=""Password"" @bind-Text=""@user.Password"">
                    <Feedback>
                        <ValidationError />
                    </Feedback>
                </TextEdit>
            </FieldBody>
        </Field>
    </Validation>
    <Validation>
        <Field Horizontal=""true"">
            <FieldLabel ColumnSize=""ColumnSize.Is2"">Re Password</FieldLabel>
            <FieldBody ColumnSize=""ColumnSize.Is10"">
                <TextEdit Role=""TextRole.Password"" Placeholder=""Retype password"" @bind-Text=""@user.ConfirmPassword"">
                    <Feedback>
                        <ValidationError />
                    </Feedback>
                </TextEdit>
            </FieldBody>
        </Field>
    </Validation>
</Validations>
@code{
    User user = new User();

    public class User
    {
        [Required]
        [StringLength( 10, ErrorMessage = ""Name is too long."" )]
        public string Name { get; set; }

        [Required]
        [EmailAddress( ErrorMessage = ""Invalid email."" )]
        public string Email { get; set; }

        [Required( ErrorMessage = ""Password is required"" )]
        [StringLength( 8, ErrorMessage = ""Must be between 5 and 8 characters"", MinimumLength = 5 )]
        [DataType( DataType.Password )]
        public string Password { get; set; }

        [Required( ErrorMessage = ""Confirm Password is required"" )]
        [StringLength( 8, ErrorMessage = ""Must be between 5 and 8 characters"", MinimumLength = 5 )]
        [DataType( DataType.Password )]
        [Compare( ""Password"" )]
        public string ConfirmPassword { get; set; }

        [Required]
        public string Title { get; set; }

        [Range( typeof( bool ), ""true"", ""true"", ErrorMessage = ""You gotta tick the box!"" )]
        public bool TermsAndConditions { get; set; }
    }
}";

        public const string LocalizationValidationExample = @"@using Blazorise.Localization

<Validation MessageLocalizer=""@Localize"">
</Validation>
@code{
    [Inject] ITextLocalizer<LocalizationValidationExample> L { get; set; }

    string Localize( string message, IEnumerable<string> arguments )
    {
        // You should probably do null checks here!
        return string.Format( L[message], arguments.ToArray() );
    }
}";

        public const string ManualValidationExample = @"<Validations @ref=""validations"" Mode=""ValidationMode.Manual"">
    <Validation Validator=""@ValidationRule.IsNotEmpty"">
        <Field>
            <TextEdit Placeholder=""Enter first name"" />
        </Field>
    </Validation>
    <Validation Validator=""@ValidationRule.IsNotEmpty"">
        <Field>
            <TextEdit Placeholder=""Enter last name"" />
        </Field>
    </Validation>
    <Button Color=""Color.Primary"" Clicked=""@Submit"">Submit</Button>
</Validations>
@code{
    Validations validations;

    void Submit()
    {
        if ( validations.ValidateAll() )
        {
            // do something
        }
    }
}";

        public const string PatternValidationExample = @"<Validation UsePattern=""true"">
    <TextEdit Pattern=""[A-Za-z]{3}"">
        <Feedback>
            <ValidationError>Pattern does not match!</ValidationError>
        </Feedback>
    </TextEdit>
</Validation>";

        public const string ValidationFeedbackExample = @"<Validation Validator=""@ValidateCheck"">
    <Check TValue=""bool"">
        <ChildContent>
            Check me out
        </ChildContent>
        <Feedback>
            <ValidationError>You must check me out!</ValidationError>
        </Feedback>
    </Check>
</Validation>
@code{
    void ValidateCheck( ValidatorEventArgs e )
    {
        // ...
    }
}";

        public const string ValidationRulesExample = @"<Validation Validator=""@ValidationRule.IsNotEmpty"">
    ...
</Validation>";

        public const string ValidationSummaryExample = @"<Validations Mode=""ValidationMode.Manual"">
    <ValidationSummary Label=""Following error occurs..."" />

    @*other validation fields*@
</Validations>";

        public const string AutocompleteExample = @"<Autocomplete TItem=""MySelectModel""
              TValue=""string""
              Data=""@myDdlData""
              TextField=""@(( item ) => item.MyTextField)""
              ValueField=""@(( item ) => item.MyTextField)""
              SelectedValue=""@selectedSearchValue""
              SelectedValueChanged=""@MySearchHandler""
              @bind-SelectedText=""selectedAutoCompleteText""
              Placeholder=""Search...""
              Filter=""AutocompleteFilter.StartsWith""
              FreeTyping=""true""
              CustomFilter=""@(( item, searchValue ) => item.MyTextField.IndexOf( searchValue, 0, StringComparison.CurrentCultureIgnoreCase ) >= 0 )"">
    <NotFoundContent> Sorry... @context was not found! :( </NotFoundContent>
</Autocomplete>

<Field Horizontal=""true"">
    <FieldBody ColumnSize=""ColumnSize.Is12"">
        Selected search value: @selectedSearchValue
    </FieldBody>
    <FieldBody ColumnSize=""ColumnSize.Is12"">
        Selected text value: @selectedAutoCompleteText
    </FieldBody>
</Field>

@code{
    public class MySelectModel
    {
        public int MyValueField { get; set; }
        public string MyTextField { get; set; }
    }

    static string[] Countries = { ""Albania"", ""Andorra"", ""Armenia"", ""Austria"", ""Azerbaijan"", ""Belarus"", ""Belgium"", ""Bosnia & Herzegovina"", ""Bulgaria"", ""Croatia"", ""Cyprus"", ""Czech Republic"", ""Denmark"", ""Estonia"", ""Finland"", ""France"", ""Georgia"", ""Germany"", ""Greece"", ""Hungary"", ""Iceland"", ""Ireland"", ""Italy"", ""Kosovo"", ""Latvia"", ""Liechtenstein"", ""Lithuania"", ""Luxembourg"", ""Macedonia"", ""Malta"", ""Moldova"", ""Monaco"", ""Montenegro"", ""Netherlands"", ""Norway"", ""Poland"", ""Portugal"", ""Romania"", ""Russia"", ""San Marino"", ""Serbia"", ""Slovakia"", ""Slovenia"", ""Spain"", ""Sweden"", ""Switzerland"", ""Turkey"", ""Ukraine"", ""United Kingdom"", ""Vatican City"" };
    IEnumerable<MySelectModel> myDdlData = Enumerable.Range( 1, Countries.Length ).Select( x => new MySelectModel { MyTextField = Countries[x - 1], MyValueField = x } );

    string selectedSearchValue { get; set; }
    string selectedAutoCompleteText { get; set; }

    void MySearchHandler( string newValue )
    {
        selectedSearchValue = newValue;
    }
}";

        public const string ChartExample = @"<Markdown Value=""@markdownValue"" ValueChanged=""@OnMarkdownValueChanged"" />

@code{
    string markdownValue = ""# EasyMDE \n Go ahead, play around with the editor! Be sure to check out **bold**, *italic*, [links](https://google.com) and all the other features. You can type the Markdown syntax, use the toolbar, or use shortcuts like `ctrl-b` or `cmd-b`."";

    string markdownHtml;

    protected override void OnInitialized()
    {
        markdownHtml = Markdig.Markdown.ToHtml( markdownValue ?? string.Empty );

        base.OnInitialized();
    }

    Task OnMarkdownValueChanged( string value )
    {
        markdownValue = value;

        markdownHtml = Markdig.Markdown.ToHtml( markdownValue ?? string.Empty );

        return Task.CompletedTask;
    }
}";

        public const string DropdownListExample = @"<DropdownList TItem=""MySelectModel"" TValue=""int""
              Data=""@myDdlData""
              TextField=""@((item)=>item.MyTextField)""
              ValueField=""@((item)=>item.MyValueField)""
              SelectedValue=""@selectedDropValue""
              SelectedValueChanged=""@MyDropValueChangedHandler""
              Color=""Color.Primary"">
    Select item
</DropdownList>

<Field Horizontal=""true"">
    <FieldBody ColumnSize=""ColumnSize.Is12"">
        Selected item: @selectedDropValue
    </FieldBody>
    <FieldBody ColumnSize=""ColumnSize.Is12"">
        Selected value: @Countries[selectedDropValue - 1]
    </FieldBody>
</Field>

@code{
    public class MySelectModel
    {
        public int MyValueField { get; set; }
        public string MyTextField { get; set; }
    }

    static string[] Countries = { ""Albania"", ""Andorra"", ""Armenia"", ""Austria"", ""Azerbaijan"", ""Belarus"", ""Belgium"", ""Bosnia & Herzegovina"", ""Bulgaria"", ""Croatia"", ""Cyprus"", ""Czech Republic"", ""Denmark"", ""Estonia"", ""Finland"", ""France"", ""Georgia"", ""Germany"", ""Greece"", ""Hungary"", ""Iceland"", ""Ireland"", ""Italy"", ""Kosovo"", ""Latvia"", ""Liechtenstein"", ""Lithuania"", ""Luxembourg"", ""Macedonia"", ""Malta"", ""Moldova"", ""Monaco"", ""Montenegro"", ""Netherlands"", ""Norway"", ""Poland"", ""Portugal"", ""Romania"", ""Russia"", ""San Marino"", ""Serbia"", ""Slovakia"", ""Slovenia"", ""Spain"", ""Sweden"", ""Switzerland"", ""Turkey"", ""Ukraine"", ""United Kingdom"", ""Vatican City"" };
    IEnumerable<MySelectModel> myDdlData = Enumerable.Range( 1, Countries.Length ).Select( x => new MySelectModel { MyTextField = Countries[x - 1], MyValueField = x } );

    int selectedDropValue { get; set; } = 2;

    void MyDropValueChangedHandler( int newValue )
    {
        selectedDropValue = newValue;
    }
}";

        public const string IconBasicExample = @"<Icon Name=""IconName.Mail"" />";

        public const string IconCustomExample = @"<Icon Name=""@(""fa-phone"")"" />";

        public const string IconNamesExample = @"<Icon Name=""Blazorise.Icons.FontAwesome.FontAwesomeIcons.Voicemail"" />";

        public const string IconStyleExample = @"<Icon Name=""IconName.Mail"" IconStyle=""IconStyle.Regular"" />";

        public const string MarkdownExample = @"<Markdown Value=""@markdownValue"" ValueChanged=""@OnMarkdownValueChanged"" />

@code{
    string markdownValue = ""# EasyMDE \n Go ahead, play around with the editor! Be sure to check out **bold**, *italic*, [links](https://google.com) and all the other features. You can type the Markdown syntax, use the toolbar, or use shortcuts like `ctrl-b` or `cmd-b`."";

    string markdownHtml;

    protected override void OnInitialized()
    {
        markdownHtml = Markdig.Markdown.ToHtml( markdownValue ?? string.Empty );

        base.OnInitialized();
    }

    Task OnMarkdownValueChanged( string value )
    {
        markdownValue = value;

        markdownHtml = Markdig.Markdown.ToHtml( markdownValue ?? string.Empty );

        return Task.CompletedTask;
    }
}";

        public const string BasicMessageServiceExample = @"<Button Color=""Color.Primary"" Clicked=""@ShowInfoMessage"">Say hi!</Button>
<Button Color=""Color.Danger"" Clicked=""@ShowConfirmMessage"">Confirm</Button>

@code{
    [Inject] IMessageService MessageService { get; set; }

    Task ShowInfoMessage()
    {
        return MessageService.Info( ""This is a simple info message!"", ""Hello"" );
    }

    async Task ShowConfirmMessage()
    {
        if ( await MessageService.Confirm( ""Are you sure you want to confirm?"", ""Confirmation"" ) )
        {
            Console.WriteLine( ""OK Clicked"" );
        }
        else
        {
            Console.WriteLine( ""Cancel Clicked"" );
        }
    }
}";

        public const string MessageServiceUsageExample = @"<Router AppAssembly=""typeof(App).Assembly"">
    ...
</Router>

<MessageAlert />";

        public const string BasicNotificationServiceExample = @"<Button Color=""Color.Warning"" Clicked=""@ShowWarningNotification"">Show alert!</Button>

@code{
    [Inject] INotificationService NotificationService { get; set; }

    Task ShowWarningNotification()
    {
        return NotificationService.Warning( ""This is a simple notification message!"", ""Hello"" );
    }
}";

        public const string NotificationServiceInstallationExample = @"Install-Package Blazorise.Components";

        public const string NotificationServiceUsageExample = @"<Router AppAssembly=""typeof(App).Assembly"">
    ...
</Router>

<NotificationAlert />";

        public const string BasicPageProgressServiceExample = @"<Button Color=""Color.Primary"" Clicked=""@SetPageProgress25"">25 %</Button>
<Button Color=""Color.Primary"" Clicked=""@SetPageProgress50"">50 %</Button>
<Button Color=""Color.Primary"" Clicked=""@SetPageProgress75"">75 %</Button>
<Button Color=""Color.Primary"" Clicked=""@SetPageProgress100"">100 %</Button>

<Button Color=""Color.Secondary"" Clicked=""@SetPageProgressIndeterminate"">Indeterminate</Button>

<Button Color=""Color.Secondary"" Clicked=""@SetPageProgressHidden"">Hide</Button>

@code{
    [Inject] IPageProgressService PageProgressService { get; set; }

    Task SetPageProgress25()
    {
        return PageProgressService.Go( 25, options => { options.Color = Color.Warning; } );
    }

    Task SetPageProgress50()
    {
        return PageProgressService.Go( 50, options => { options.Color = Color.Warning; } );
    }

    Task SetPageProgress75()
    {
        return PageProgressService.Go( 75, options => { options.Color = Color.Warning; } );
    }

    Task SetPageProgress100()
    {
        return PageProgressService.Go( 100, options => { options.Color = Color.Warning; } );
    }

    Task SetPageProgressIndeterminate()
    {
        return PageProgressService.Go( null, options => { options.Color = Color.Warning; } );
    }

    Task SetPageProgressHidden()
    {
        // setting it to -1 will hide the progress bar
        return PageProgressService.Go( -1 );
    }
}";

        public const string PageProgressServiceUsageExample = @"<Router AppAssembly=""typeof(App).Assembly"">
    ...
</Router>

<PageProgressAlert />";

    }
}
