<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="..\..\..\Build\Blazorise.props" />

  <PropertyGroup>
    <PackageTags>blazorise blazor components ribbon toolbar</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Blazorise\Blazorise.csproj" />
    <ProjectReference Include="..\Blazorise.Animate\Blazorise.Animate.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Localization\Ribbon\*.json" />
  </ItemGroup>

</Project>