#region Using directives
using System.Collections.Generic;
using System.Linq;
using Blazorise.Providers;
#endregion

namespace Blazorise.Icons.Fabric;

class FabricIconProvider : BaseIconProvider
{
    #region Members

    private static Dictionary<IconName, string> names = new()
    {
        { IconName.Add, FabricIcons.Add },
        { IconName.Adjust, FabricIcons.PhotoFilter },
        { IconName.AlignCenter, FabricIcons.TextAlignCenter },
        { IconName.AlignJustify, FabricIcons.TextAlignJustify },
        { IconName.AlignLeft, FabricIcons.TextAlignLeft },
        { IconName.AlignRight, FabricIcons.TextAlignRight },
        { IconName.AngleDown, FabricIcons.TriangleDown },
        { IconName.AngleLeft, FabricIcons.TriangleLeft },
        { IconName.AngleRight, FabricIcons.TriangleRight},
        { IconName.AngleUp, FabricIcons.TriangleUp },
        { IconName.Archive, FabricIcons.Archive },
        //{ IconName.ArrowAltCircleDown, FabricIcons.arrowdown },
        { IconName.ArrowDown, FabricIcons.ArrowDown },
        { IconName.ArrowLeft, FabricIcons.ArrowLeft },
        { IconName.ArrowRight, FabricIcons.ArrowRight },
        { IconName.ArrowUp, FabricIcons.ArrowUp },
        //{ IconName.Baby, FabricIcons.Baby },
        //{ IconName.BabyCarriage, FabricIcons.BabyCarriage },
        //{ IconName.Backspace, FabricIcons.Backspace },
        { IconName.Backward, FabricIcons.Rewind },
        { IconName.BalanceScale, FabricIcons.Scales },
        { IconName.Ban, FabricIcons.Warning },
        { IconName.BandAid, FabricIcons.BriefcaseMedical },
        { IconName.Bars, FabricIcons.Navigation },
        { IconName.BatteryFull, FabricIcons.Battery10 },
        { IconName.Bell, FabricIcons.ServiceBell },
        //{ IconName.BellSlash, FabricIcons.BellSlash },
        { IconName.Biking, FabricIcons.VehicleBicycle },
        { IconName.BirthdayCake, FabricIcons.FoodCake },
        { IconName.Bold, FabricIcons.TextBold },
        { IconName.Bolt, FabricIcons.TextGrammarLightning },
        { IconName.Book, FabricIcons.Book },
        { IconName.Bookmark, FabricIcons.Bookmark },
        { IconName.BookReader, FabricIcons.ImmersiveReader },
        { IconName.BorderAll, FabricIcons.BorderAll },
        { IconName.BorderNone, FabricIcons.BorderNone },
        { IconName.BorderStyle, FabricIcons.BorderTopBottom },
        { IconName.Briefcase, FabricIcons.Briefcase },
        { IconName.Brush, FabricIcons.PaintBrush },
        { IconName.Bug, FabricIcons.Bug },
        { IconName.Building, FabricIcons.Building },
        { IconName.Bus, FabricIcons.VehicleBus },
        { IconName.CalendarCheck, FabricIcons.CalendarCheckmark },
        { IconName.CalendarDay, FabricIcons.CalendarDay },
        { IconName.CalendarTimes, FabricIcons.CalendarAgenda },
        { IconName.CalendarWeek, FabricIcons.CalendarWeekNumbers },
        { IconName.Camera, FabricIcons.Camera },
        { IconName.CameraRetro, FabricIcons.Camera },
        { IconName.Car, FabricIcons.VehicleCar },
        { IconName.CaretSquareRight, FabricIcons.CaretRight },
        { IconName.CartPlus, FabricIcons.Cart },
        { IconName.Chair, FabricIcons.Couch },
        { IconName.ChartPie, FabricIcons.DataPie },
        { IconName.Check, FabricIcons.Checkmark },
        { IconName.CheckCircle, FabricIcons.CheckmarkCircle },
        { IconName.CheckDouble, FabricIcons.CheckmarkStarburst },
        { IconName.CheckSquare, FabricIcons.CheckmarkSquare },
        { IconName.ChevronLeft, FabricIcons.ChevronLeft },
        { IconName.ChevronRight, FabricIcons.ChevronRight },
        { IconName.ChevronUp, FabricIcons.ChevronUp },
        { IconName.ChevronDown, FabricIcons.ChevronDown },
        { IconName.Circle, FabricIcons.Circle },
        { IconName.City, FabricIcons.City },
        { IconName.Clear, FabricIcons.Dismiss },
        { IconName.ClinicMedical, FabricIcons.BriefcaseMedical },
        { IconName.Clock, FabricIcons.Clock },
        { IconName.ClosedCaptioning, FabricIcons.ClosedCaption },
        { IconName.Cloud, FabricIcons.Cloud },
        { IconName.CloudDownloadAlt, FabricIcons.CloudArrowDown },
        { IconName.CloudUploadAlt, FabricIcons.CloudArrowUp },
        { IconName.Cocktail, FabricIcons.DrinkMargarita },
        { IconName.Code, FabricIcons.Code },
        { IconName.Coffee, FabricIcons.DrinkCoffee },
        { IconName.Comment, FabricIcons.Comment },
        { IconName.CommentAlt, FabricIcons.CommentArrowLeft },
        { IconName.Comments, FabricIcons.CommentMultiple },
        //{ IconName.CompactDisc, FabricIcons.CompactDisc },
        { IconName.Compass, FabricIcons.CompassNorthwest },
        { IconName.Compress, FabricIcons.ArrowMinimize },
        //{ IconName.Copyright, FabricIcons.Copyright },
        { IconName.CreditCard, FabricIcons.Payment },
        { IconName.Crop, FabricIcons.Crop },
        { IconName.Dashboard, FabricIcons.LayoutColumnTwoSplitLeft },
        { IconName.Delete, FabricIcons.Delete },
        { IconName.Desktop, FabricIcons.Desktop },
        { IconName.Dice, FabricIcons.CubeQuick },
        { IconName.Directions, FabricIcons.Directions },
        { IconName.Dog, FabricIcons.AnimalDog },
        { IconName.DollarSign, FabricIcons.CurrencyDollarEuro },
        { IconName.DotCircle, FabricIcons.Record },
        { IconName.Download, FabricIcons.ArrowDownload },
        { IconName.Dumbbell, FabricIcons.Dumbbell },
        { IconName.Edit, FabricIcons.Edit },
        //{ IconName.Eject, FabricIcons.Eject },
        { IconName.Ethernet, FabricIcons.Wifi1 },
        { IconName.EuroSign, FabricIcons.CurrencyDollarEuro },
        { IconName.Exclamation, FabricIcons.ShieldError },
        { IconName.ExclamationCircle, FabricIcons.ErrorCircle },
        { IconName.ExclamationTriangle, FabricIcons.Warning },
        { IconName.Expand, FabricIcons.ArrowMaximize },
        { IconName.ExpandArrowsAlt, FabricIcons.FullScreenMaximize },
        { IconName.ExpandLess, FabricIcons.ChevronUp },
        { IconName.ExpandMore, FabricIcons.ChevronDown },
        { IconName.ExternalLinkSquareAlt, FabricIcons.LinkSquare },
        { IconName.Eye, FabricIcons.Eye },
        { IconName.EyeSlash, FabricIcons.EyeOff },
        { IconName.FastForward, FabricIcons.FastForward },
        { IconName.FileAlt, FabricIcons.Document },
        { IconName.FileDownload, FabricIcons.DocumentArrowDown },
        { IconName.FilePdf, FabricIcons.DocumentPdf },
        { IconName.FileUpload, FabricIcons.DocumentArrowUp },
        { IconName.Film, FabricIcons.Filmstrip },
        { IconName.Filter, FabricIcons.Filter },
        { IconName.Fingerprint, FabricIcons.Fingerprint },
        { IconName.Fire, FabricIcons.Fire },
        { IconName.Flag, FabricIcons.Flag },
        { IconName.Flask, FabricIcons.Beaker },
        { IconName.Folder, FabricIcons.Folder },
        { IconName.FolderOpen, FabricIcons.FolderOpen },
        { IconName.FolderPlus, FabricIcons.FolderAdd },
        { IconName.Forward, FabricIcons.FastForward },
        { IconName.Frown, FabricIcons.EmojiSad },
        { IconName.FrownOpen, FabricIcons.EmojiSadSlight },
        { IconName.Gamepad, FabricIcons.Games },
        { IconName.GasPump, FabricIcons.GasPump },
        { IconName.Gavel, FabricIcons.Gavel },
        { IconName.Gift, FabricIcons.Gift },
        { IconName.Grin, FabricIcons.Emoji },
        { IconName.GripLines, FabricIcons.SplitHorizontal },
        { IconName.GripVertical, FabricIcons.SplitVertical },
        { IconName.HandPaper, FabricIcons.HandLeft },
        { IconName.HandsHelping, FabricIcons.Handshake },
        { IconName.Headphones, FabricIcons.Headphones },
        { IconName.Headset, FabricIcons.Headset },
        { IconName.Heart, FabricIcons.Heart },
        { IconName.Highlighter, FabricIcons.Highlight },
        { IconName.History, FabricIcons.History },
        { IconName.Home, FabricIcons.Home },
        { IconName.Hospital, FabricIcons.BuildingPeople },
        { IconName.Hotel, FabricIcons.Building },
        { IconName.HotTub, FabricIcons.Showerhead },
        { IconName.Hourglass, FabricIcons.Hourglass },
        { IconName.IdCard, FabricIcons.ContactCard },
        { IconName.Image, FabricIcons.Image },
        { IconName.Images, FabricIcons.ImageSearch },
        { IconName.Inbox, FabricIcons.MailInbox },
        { IconName.Indent, FabricIcons.TextIndentIncrease },
        { IconName.Infinity, FabricIcons.NumberSymbol },
        { IconName.Info, FabricIcons.Info },
        { IconName.InfoCircle, FabricIcons.InfoShield },
        { IconName.Italic, FabricIcons.TextItalic },
        { IconName.Key, FabricIcons.Key },
        { IconName.Keyboard, FabricIcons.Keyboard },
        { IconName.Language, FabricIcons.LocalLanguage },
        { IconName.Laptop, FabricIcons.Laptop },
        { IconName.LaptopCode, FabricIcons.LaptopSettings },
        { IconName.Laugh, FabricIcons.EmojiLaugh },
        { IconName.LayerGroup, FabricIcons.Layer },
        { IconName.Lightbulb, FabricIcons.Lightbulb },
        { IconName.Link, FabricIcons.Link },
        { IconName.List, FabricIcons.List },
        { IconName.ListOl, FabricIcons.TextBulletList },
        { IconName.ListUl, FabricIcons.TextNumberListLtr },
        { IconName.LocationArrow, FabricIcons.LocationArrow },
        { IconName.Lock, FabricIcons.LockClosed },
        { IconName.LockOpen, FabricIcons.LockOpen },
        { IconName.Mail, FabricIcons.Mail },
        { IconName.Map, FabricIcons.Map },
        { IconName.MapMarker, FabricIcons.Location },
        { IconName.MapMarkerAlt, FabricIcons.MyLocation },
        { IconName.Memory, FabricIcons.Storage },
        { IconName.Microphone, FabricIcons.SlideMicrophone },
        { IconName.MicrophoneSlash, FabricIcons.BookOpenMicrophone },
        //{ IconName.MinusCircle, FabricIcons.minus },
        //{ IconName.MinusSquare, FabricIcons.MinusSquare },
        { IconName.MoneyBillAlt, FabricIcons.Money },
        { IconName.MoreHorizontal, FabricIcons.MoreHorizontal },
        { IconName.MoreVertical, FabricIcons.MoreVertical },
        { IconName.Motorcycle, FabricIcons.VehicleBicycle },
        //{ IconName.Mouse, FabricIcons.Mouse },
        { IconName.Music, FabricIcons.MusicNote2 },
        { IconName.PaintBrush, FabricIcons.PaintBrush },
        { IconName.PaintRoller, FabricIcons.PaintBucket },
        { IconName.Palette, FabricIcons.Color },
        //{ IconName.Paperclip, FabricIcons.Paperclip },
        { IconName.PaperPlane, FabricIcons.Send },
        { IconName.Parking, FabricIcons.VehicleCarParking },
        { IconName.Pause, FabricIcons.Pause },
        { IconName.PauseCircle, FabricIcons.PauseCircle },
        { IconName.Pen, FabricIcons.Pen },
        { IconName.Phone, FabricIcons.Call },
        { IconName.PhoneAlt, FabricIcons.Call },
        { IconName.PizzaSlice, FabricIcons.FoodPizza },
        { IconName.Plane, FabricIcons.Airplane },
        { IconName.PlaneArrival, FabricIcons.AirplaneLanding },
        { IconName.PlaneDeparture, FabricIcons.AirplaneTakeOff },
        { IconName.Play, FabricIcons.Play },
        { IconName.PlayCircle, FabricIcons.PlayCircle },
        { IconName.Plug, FabricIcons.PlugConnected },
        { IconName.PlusCircle, FabricIcons.AddCircle },
        { IconName.PlusSquare, FabricIcons.AddSquare },
        { IconName.Poll, FabricIcons.Poll },
        { IconName.Portrait, FabricIcons.PersonSquare },
        { IconName.Print, FabricIcons.Print },
        { IconName.PuzzlePiece, FabricIcons.PuzzlePiece },
        { IconName.QuestionCircle, FabricIcons.QuestionCircle },
        { IconName.QuoteRight, FabricIcons.TextQuote },
        { IconName.Random, FabricIcons.NumberCircle0 },
        { IconName.Receipt, FabricIcons.Receipt },
        { IconName.Redo, FabricIcons.ArrowRedo },
        { IconName.Remove, FabricIcons.Delete },
        { IconName.RemoveFormat, FabricIcons.ClearFormatting },
        { IconName.Reply, FabricIcons.ArrowReply },
        { IconName.ReplyAll, FabricIcons.ArrowReplyAll },
        { IconName.Restroom, FabricIcons.BreakoutRoom },
        { IconName.Rss, FabricIcons.Rss },
        { IconName.RulerHorizontal, FabricIcons.Ruler },
        { IconName.Running, FabricIcons.Run },
        { IconName.Satellite, FabricIcons.Rocket },
        { IconName.Save, FabricIcons.Save },
        { IconName.School, FabricIcons.LearningApp },
        { IconName.SdCard, FabricIcons.Sim },
        { IconName.Search, FabricIcons.Search },
        //{ IconName.SearchMinus, FabricIcons.SearchMinus },
        //{ IconName.SearchPlus, FabricIcons.SearchPlus },
        { IconName.Seedling, FabricIcons.PlantGrass },
        { IconName.Server, FabricIcons.Server },
        { IconName.Shapes, FabricIcons.Shapes },
        { IconName.Share, FabricIcons.Share },
        { IconName.ShareAlt, FabricIcons.ShareIos },
        { IconName.ShieldAlt, FabricIcons.Shield },
        { IconName.Ship, FabricIcons.VehicleShip },
        { IconName.ShoppingBag, FabricIcons.ShoppingBag },
        { IconName.ShoppingBasket, FabricIcons.ShoppingBag },
        { IconName.ShoppingCart, FabricIcons.Cart },
        { IconName.ShuttleVan, FabricIcons.VehicleTruck },
        { IconName.SimCard, FabricIcons.Sim },
        //{ IconName.SliderHorizontal, FabricIcons.Slider },
        { IconName.Smartphone, FabricIcons.Phone },
        { IconName.Smile, FabricIcons.EmojiSmileSlight },
        { IconName.Smoking, FabricIcons.Fire },
        { IconName.SmokingBan, FabricIcons.Fireplace },
        { IconName.Sms, FabricIcons.Comment },
        { IconName.Snowflake, FabricIcons.WeatherSnowflake },
        { IconName.Sort, FabricIcons.ArrowSort },
        { IconName.SortAlphaDown, FabricIcons.TextSortDescending },
        { IconName.SortAmountDownAlt, FabricIcons.TextSortAscending },
        { IconName.SortDown, FabricIcons.ArrowSortDown },
        { IconName.SortUp, FabricIcons.ArrowSortUp },
        //{ IconName.Spa, FabricIcons.Spa },
        { IconName.SpellCheck, FabricIcons.Check },
        { IconName.Square, FabricIcons.Square },
        { IconName.Star, FabricIcons.Star },
        { IconName.StarHalf, FabricIcons.StarHalf },
        { IconName.StepBackward, FabricIcons.ArrowStepInLeft },
        { IconName.StepForward, FabricIcons.ArrowStepInRight },
        { IconName.StickyNote, FabricIcons.Sticker },
        { IconName.Stop, FabricIcons.Stop },
        { IconName.Store, FabricIcons.BuildingShop },
        { IconName.StoreAlt, FabricIcons.StoreMicrosoft },
        { IconName.Stream, FabricIcons.Stream },
        //{ IconName.StreetView, FabricIcons.street },
        { IconName.Strikethrough, FabricIcons.TextStrikethrough },
        { IconName.Subscript, FabricIcons.TextSubscript },
        { IconName.Subway, FabricIcons.VehicleSubway },
        { IconName.Suitcase, FabricIcons.Briefcase },
        { IconName.Sun, FabricIcons.WeatherSunny },
        { IconName.Superscript, FabricIcons.TextSuperscript },
        { IconName.SwimmingPool, FabricIcons.SwimmingPool },
        { IconName.Sync, FabricIcons.ArrowSync },
        { IconName.SyncAlt, FabricIcons.FolderSync },
        { IconName.Tablet, FabricIcons.Tablet },
        { IconName.Tag, FabricIcons.Tag },
        { IconName.Taxi, FabricIcons.VehicleCab },
        { IconName.TextHeight, FabricIcons.AutoFitHeight },
        { IconName.ThumbsDown, FabricIcons.ThumbLike },
        { IconName.ThumbsUp, FabricIcons.ThumbDislike },
        { IconName.TicketAlt, FabricIcons.TicketDiagonal },
        { IconName.Times, FabricIcons.Dismiss },
        { IconName.TimesCircle, FabricIcons.DismissCircle },
        { IconName.Tint, FabricIcons.Eyedropper },
        { IconName.TintSlash, FabricIcons.EyedropperOff },
        { IconName.TrafficLight, FabricIcons.RoadCone },
        { IconName.Train, FabricIcons.DriveTrain },
        { IconName.Tram, FabricIcons.VehicleSubway },
        { IconName.Tree, FabricIcons.TreeDeciduous },
        { IconName.Truck, FabricIcons.VehicleTruck },
        { IconName.Tv, FabricIcons.Tv },
        { IconName.UmbrellaBeach, FabricIcons.Umbrella },
        { IconName.Underline, FabricIcons.TextUnderline },
        { IconName.Undo, FabricIcons.ArrowUndo },
        { IconName.Unlock, FabricIcons.LockOpen },
        { IconName.User, FabricIcons.Person },
        { IconName.UserCheck, FabricIcons.CheckboxPerson },
        { IconName.UserCircle, FabricIcons.PersonCircle },
        { IconName.UserFriends, FabricIcons.People },
        { IconName.UserPlus, FabricIcons.PersonAdd },
        { IconName.Users, FabricIcons.People },
        { IconName.UserTie, FabricIcons.PersonStarburst },
        //{ IconName.Utensils, FabricIcons.Utensils },
        { IconName.Video, FabricIcons.Video },
        { IconName.VideoSlash, FabricIcons.VideoOff },
        { IconName.Voicemail, FabricIcons.Voicemail },
        //{ IconName.VolumeDown, FabricIcons. },
        //{ IconName.VolumeMute, FabricIcons.VolumeDisabled },
        //{ IconName.VolumeOff, FabricIcons.Volume0 },
        //{ IconName.VolumeUp, FabricIcons.Volume3 },
        { IconName.Walking, FabricIcons.PersonWalking },
        { IconName.Wallet, FabricIcons.Wallet },
        //{ IconName.Wheelchair, FabricIcons.Wheelchair },
        { IconName.Wifi, FabricIcons.Wifi1 },
        { IconName.WineBottle, FabricIcons.DrinkWine },
        { IconName.Wrench, FabricIcons.Wrench },
    };

    private static Dictionary<IconStyle, string> styles = new()
    {
        { IconStyle.Solid, "ms-Icon ms-Icon-filled" },
        { IconStyle.Regular, "ms-Icon ms-Icon-regular" },
        { IconStyle.Light, "ms-Icon ms-Icon-light" },
        { IconStyle.DuoTone, "ms-Icon ms-Icon-duo" },
    };

    #endregion

    #region Methods

    public override string IconSize( IconSize iconSize )
    {
        return iconSize switch
        {
            Blazorise.IconSize.ExtraSmall => "ms-Icon-xs",
            Blazorise.IconSize.Small => "ms-Icon-sm",
            Blazorise.IconSize.Large => "ms-Icon-lg",
            Blazorise.IconSize.x2 => "ms-Icon-2x",
            Blazorise.IconSize.x3 => "ms-Icon-3x",
            Blazorise.IconSize.x4 => "ms-Icon-4x",
            Blazorise.IconSize.x5 => "ms-Icon-5x",
            Blazorise.IconSize.x6 => "ms-Icon-6x",
            Blazorise.IconSize.x7 => "ms-Icon-7x",
            Blazorise.IconSize.x8 => "ms-Icon-8x",
            Blazorise.IconSize.x9 => "ms-Icon-9x",
            Blazorise.IconSize.x10 => "ms-Icon-10x",
            _ => null,
        };
    }

    public override string GetIconName( IconName iconName, IconStyle iconStyle )
    {
        if ( names.TryGetValue( iconName, out var name ) )
        {
            if ( iconStyle == IconStyle.Solid )
            {
                return name.Replace( "_regular", "_filled" );
            }

            return name;
        }

        return null;
    }

    public override void SetIconName( IconName name, string newName )
    {
        names[name] = newName;
    }

    public override string GetStyleName( IconStyle iconStyle )
    {
        return null;
    }

    protected override bool ContainsStyleName( string iconName )
    {
        return iconName.Split( ' ' ).Any( x => styles.Values.Contains( x ) || new string[] { "ms-Icon-brand" }.Contains( x ) );
    }

    #endregion

    #region Properties

    public override bool IconNameAsContent => false;

    #endregion
}