#region Using directives
using System.Collections.Generic;
using System.Linq;
using Blazorise.Providers;
#endregion

namespace Blazorise.Icons.Fabric;

class FabricIconProvider : BaseIconProvider
{
    #region Members

    private static Dictionary<IconName, string> names = new()
    {
        { IconName.Add, FabricIcons.Add },
        { IconName.Adjust, FabricIcons.Contrast },
        { IconName.AlignCenter, FabricIcons.AlignCenter },
        { IconName.AlignJustify, FabricIcons.AlignJustify },
        { IconName.AlignLeft, FabricIcons.AlignLeft },
        { IconName.AlignRight, FabricIcons.AlignRight },
        { IconName.AngleDown, FabricIcons.TriangleSolidDown12 },
        { IconName.AngleLeft, FabricIcons.TriangleSolidLeft12 },
        { IconName.AngleRight, FabricIcons.TriangleSolidRight12 },
        { IconName.AngleUp, FabricIcons.TriangleSolidUp12 },
        { IconName.Archive, FabricIcons.Archive },
        //{ IconName.ArrowAltCircleDown, FabricIcons.ArrowAltCircleDown },
        { IconName.ArrowDown, FabricIcons.Down },
        //{ IconName.ArrowLeft, FabricIcons.ArrowLeft },
        //{ IconName.ArrowRight, FabricIcons.ArrowRight },
        { IconName.ArrowUp, FabricIcons.Up },
        //{ IconName.Baby, FabricIcons.Baby },
        //{ IconName.BabyCarriage, FabricIcons.BabyCarriage },
        //{ IconName.Backspace, FabricIcons.Backspace },
        { IconName.Backward, FabricIcons.Back },
        //{ IconName.BalanceScale, FabricIcons.BalanceScale },
        { IconName.Ban, FabricIcons.StatusCircleBlock },
        { IconName.BandAid, FabricIcons.Medical },
        //{ IconName.Bars, FabricIcons.Bars },
        //{ IconName.BatteryFull, FabricIcons.BatteryFull },
        //{ IconName.Bell, FabricIcons.Bell },
        //{ IconName.BellSlash, FabricIcons.BellSlash },
        //{ IconName.Biking, FabricIcons.Biking },
        { IconName.BirthdayCake, FabricIcons.BirthdayCake },
        { IconName.Bold, FabricIcons.Bold },
        { IconName.Bolt, FabricIcons.LightningBolt },
        { IconName.Book, FabricIcons.BookAnswers },
        { IconName.Bookmark, FabricIcons.SingleBookmark },
        { IconName.BookReader, FabricIcons.ReadingMode },
        { IconName.BorderAll, FabricIcons.BorderAll },
        { IconName.BorderNone, FabricIcons.BorderNone },
        { IconName.BorderStyle, FabricIcons.ToggleBorder },
        { IconName.Briefcase, FabricIcons.Suitcase },
        { IconName.Brush, FabricIcons.Brush },
        { IconName.Bug, FabricIcons.Bug },
        //{ IconName.Building, FabricIcons.Building },
        { IconName.Bus, FabricIcons.Bus },
        { IconName.CalendarCheck, FabricIcons.PrimaryCalendar },
        { IconName.CalendarDay, FabricIcons.CalendarDay },
        { IconName.CalendarTimes, FabricIcons.CalendarAgenda },
        { IconName.CalendarWeek, FabricIcons.CalendarWeek },
        { IconName.Camera, FabricIcons.Camera },
        { IconName.CameraRetro, FabricIcons.Camera },
        { IconName.Car, FabricIcons.Car },
        //{ IconName.CaretSquareRight, FabricIcons.CaretSquareRight },
        //{ IconName.CartPlus, FabricIcons.CartPlus },
        //{ IconName.Chair, FabricIcons.Chair },
        { IconName.ChartPie, FabricIcons.PieSingle },
        { IconName.Check, FabricIcons.CheckMark },
        { IconName.CheckCircle, FabricIcons.SkypeCircleCheck },
        { IconName.CheckDouble, FabricIcons.SkypeCheck },
        { IconName.CheckSquare, FabricIcons.BoxCheckmarkSolid },
        { IconName.ChevronLeft, FabricIcons.ChevronLeft },
        { IconName.ChevronRight, FabricIcons.ChevronRight },
        { IconName.ChevronUp, FabricIcons.ChevronUp },
        { IconName.ChevronDown, FabricIcons.ChevronDown },
        { IconName.Circle, FabricIcons.CircleAdditionSolid },
        { IconName.City, FabricIcons.CityNext },
        { IconName.Clear, FabricIcons.Clear },
        { IconName.ClinicMedical, FabricIcons.Hospital },
        { IconName.Clock, FabricIcons.Clock },
        { IconName.ClosedCaptioning, FabricIcons.ClosedCaption },
        { IconName.Cloud, FabricIcons.Cloud },
        { IconName.CloudDownloadAlt, FabricIcons.CloudDownload },
        { IconName.CloudUploadAlt, FabricIcons.CloudUpload },
        { IconName.Cocktail, FabricIcons.Cocktails },
        { IconName.Code, FabricIcons.Code },
        { IconName.Coffee, FabricIcons.Coffee },
        { IconName.Comment, FabricIcons.Comment },
        { IconName.CommentAlt, FabricIcons.CommentSolid },
        { IconName.Comments, FabricIcons.CommentActive },
        //{ IconName.CompactDisc, FabricIcons.CompactDisc },
        { IconName.Compass, FabricIcons.CompassNW },
        //{ IconName.Compress, FabricIcons.Compress },
        //{ IconName.Copyright, FabricIcons.Copyright },
        { IconName.CreditCard, FabricIcons.PaymentCard },
        { IconName.Crop, FabricIcons.Crop },
        { IconName.Dashboard, FabricIcons.ViewDashboard },
        { IconName.Delete, FabricIcons.Delete },
        { IconName.Desktop, FabricIcons.ThisPC },
        //{ IconName.Dice, FabricIcons.Dice },
        { IconName.Directions, FabricIcons.MapDirections },
        //{ IconName.Dog, FabricIcons.Dog },
        { IconName.DollarSign, FabricIcons.AllCurrency },
        { IconName.DotCircle, FabricIcons.Location },
        { IconName.Download, FabricIcons.Download },
        { IconName.Dumbbell, FabricIcons.Weights },
        { IconName.Edit, FabricIcons.Edit },
        //{ IconName.Eject, FabricIcons.Eject },
        { IconName.Ethernet, FabricIcons.WifiEthernet },
        { IconName.EuroSign, FabricIcons.AllCurrency },
        //{ IconName.Exclamation, FabricIcons.Exclamation },
        { IconName.ExclamationCircle, FabricIcons.StatusCircleExclamation },
        { IconName.ExclamationTriangle, FabricIcons.StatusTriangleExclamation },
        { IconName.Expand, FabricIcons.MiniExpand },
        { IconName.ExpandArrowsAlt, FabricIcons.MiniExpandMirrored },
        { IconName.ExpandLess, FabricIcons.ChevronUp },
        { IconName.ExpandMore, FabricIcons.ChevronDown },
        //{ IconName.ExternalLinkSquareAlt, FabricIcons.ExternalLinkSquareAlt },
        { IconName.Eye, FabricIcons.RedEye },
        { IconName.EyeSlash, FabricIcons.Hide3 },
        { IconName.FastForward, FabricIcons.FastForward },
        { IconName.FileAlt, FabricIcons.FileCode },
        { IconName.FileDownload, FabricIcons.DownloadDocument },
        { IconName.FilePdf, FabricIcons.PDF },
        { IconName.FileUpload, FabricIcons.OpenFile },
        { IconName.Film, FabricIcons.MyMoviesTV },
        { IconName.Filter, FabricIcons.Filter },
        { IconName.Fingerprint, FabricIcons.Fingerprint },
        { IconName.Fire, FabricIcons.FlameSolid },
        { IconName.Flag, FabricIcons.Flag },
        { IconName.Flask, FabricIcons.TestBeaker },
        { IconName.Folder, FabricIcons.Folder },
        { IconName.FolderOpen, FabricIcons.FolderOpen },
        //{ IconName.FolderPlus, FabricIcons.FolderPlus },
        { IconName.Forward, FabricIcons.Forward },
        { IconName.Frown, FabricIcons.Sad },
        { IconName.FrownOpen, FabricIcons.SadSolid },
        { IconName.Gamepad, FabricIcons.Game },
        //{ IconName.GasPump, FabricIcons.GasPump },
        //{ IconName.Gavel, FabricIcons.Gavel },
        { IconName.Gift, FabricIcons.Giftbox },
        { IconName.Grin, FabricIcons.Emoji2 },
        { IconName.GripLines, FabricIcons.GripperBarHorizontal },
        { IconName.GripVertical, FabricIcons.GripperBarVertical },
        { IconName.HandPaper, FabricIcons.HandsFree },
        //{ IconName.HandsHelping, FabricIcons.HandsHelping },
        //{ IconName.Headphones, FabricIcons.Headphones },
        { IconName.Headset, FabricIcons.Headset },
        { IconName.Heart, FabricIcons.Heart },
        { IconName.Highlighter, FabricIcons.Highlight },
        { IconName.History, FabricIcons.History },
        { IconName.Home, FabricIcons.Home },
        { IconName.Hospital, FabricIcons.Hospital },
        { IconName.Hotel, FabricIcons.Hotel },
        //{ IconName.HotTub, FabricIcons.HotTub },
        { IconName.Hourglass, FabricIcons.HourGlass },
        { IconName.IdCard, FabricIcons.ContactCard },
        { IconName.Image, FabricIcons.ImagePixel },
        { IconName.Images, FabricIcons.ImageSearch },
        { IconName.Inbox, FabricIcons.Inbox },
        { IconName.Indent, FabricIcons.IncreaseIndent },
        //{ IconName.Infinity, FabricIcons.Infinity },
        { IconName.Info, FabricIcons.Info },
        { IconName.InfoCircle, FabricIcons.InfoSolid },
        { IconName.Italic, FabricIcons.Italic },
        //{ IconName.Key, FabricIcons.Key },
        { IconName.Keyboard, FabricIcons.KeyboardClassic },
        { IconName.Language, FabricIcons.LocaleLanguage },
        { IconName.Laptop, FabricIcons.LaptopSelected },
        { IconName.LaptopCode, FabricIcons.LaptopSecure },
        { IconName.Laugh, FabricIcons.Emoji },
        { IconName.LayerGroup, FabricIcons.MapLayers },
        { IconName.Lightbulb, FabricIcons.Lightbulb },
        { IconName.Link, FabricIcons.Link },
        { IconName.List, FabricIcons.List },
        { IconName.ListOl, FabricIcons.NumberedList },
        { IconName.ListUl, FabricIcons.BulletedList },
        { IconName.LocationArrow, FabricIcons.LocationDot },
        { IconName.Lock, FabricIcons.Lock },
        { IconName.LockOpen, FabricIcons.Unlock },
        { IconName.Mail, FabricIcons.Mail },
        { IconName.Map, FabricIcons.Nav2DMapView },
        { IconName.MapMarker, FabricIcons.MapPin },
        { IconName.MapMarkerAlt, FabricIcons.MapPin12 },
        //{ IconName.Memory, FabricIcons.Memory },
        { IconName.Microphone, FabricIcons.Microphone },
        //{ IconName.MicrophoneSlash, FabricIcons.MicrophoneSlash },
        //{ IconName.MinusCircle, FabricIcons.MinusCircle },
        //{ IconName.MinusSquare, FabricIcons.MinusSquare },
        //{ IconName.MoneyBillAlt, FabricIcons.MoneyBillAlt },
        //{ IconName.MoreHorizontal, FabricIcons.EllipsisH },
        //{ IconName.MoreVertical, FabricIcons.EllipsisV },
        //{ IconName.Motorcycle, FabricIcons.Motorcycle },
        //{ IconName.Mouse, FabricIcons.Mouse },
        //{ IconName.Music, FabricIcons.Music },
        //{ IconName.PaintBrush, FabricIcons.PaintBrush },
        //{ IconName.PaintRoller, FabricIcons.PaintRoller },
        //{ IconName.Palette, FabricIcons.Palette },
        //{ IconName.Paperclip, FabricIcons.Paperclip },
        //{ IconName.PaperPlane, FabricIcons.PaperPlane },
        //{ IconName.Parking, FabricIcons.Parking },
        { IconName.Pause, FabricIcons.Pause },
        //{ IconName.PauseCircle, FabricIcons.PauseCircle },
        //{ IconName.Pen, FabricIcons.Pen },
        { IconName.Phone, FabricIcons.Phone },
        //{ IconName.PhoneAlt, FabricIcons.PhoneAlt },
        //{ IconName.PizzaSlice, FabricIcons.PizzaSlice },
        //{ IconName.Plane, FabricIcons.Plane },
        //{ IconName.PlaneArrival, FabricIcons.PlaneArrival },
        //{ IconName.PlaneDeparture, FabricIcons.PlaneDeparture },
        { IconName.Play, FabricIcons.Play },
        //{ IconName.PlayCircle, FabricIcons.PlayCircle },
        { IconName.Plug, FabricIcons.Plug },
        //{ IconName.PlusCircle, FabricIcons.PlusCircle },
        //{ IconName.PlusSquare, FabricIcons.PlusSquare },
        //{ IconName.Poll, FabricIcons.Poll },
        //{ IconName.Portrait, FabricIcons.Portrait },
        { IconName.Print, FabricIcons.Print },
        //{ IconName.PuzzlePiece, FabricIcons.PuzzlePiece },
        //{ IconName.QuestionCircle, FabricIcons.QuestionCircle },
        //{ IconName.QuoteRight, FabricIcons.QuoteRight },
        //{ IconName.Random, FabricIcons.Random },
        { IconName.Receipt, FabricIcons.ReceiptProcessing },
        { IconName.Redo, FabricIcons.Redo },
        { IconName.Remove, FabricIcons.Remove },
        { IconName.RemoveFormat, FabricIcons.PageRemove },
        { IconName.Reply, FabricIcons.Reply },
        { IconName.ReplyAll, FabricIcons.ReplyAll },
        //{ IconName.Restroom, FabricIcons.Restroom },
        { IconName.Rss, FabricIcons.RSSFeed },
        //{ IconName.RulerHorizontal, FabricIcons.RulerHorizontal },
        { IconName.Running, FabricIcons.Running },
        //{ IconName.Satellite, FabricIcons.Satellite },
        { IconName.Save, FabricIcons.Save },
        { IconName.School, FabricIcons.SchoolDataSyncLogo },
        { IconName.SdCard, FabricIcons.SDCard },
        { IconName.Search, FabricIcons.Search },
        //{ IconName.SearchMinus, FabricIcons.SearchMinus },
        //{ IconName.SearchPlus, FabricIcons.SearchPlus },
        //{ IconName.Seedling, FabricIcons.Seedling },
        { IconName.Server, FabricIcons.Server },
        { IconName.Shapes, FabricIcons.Shapes },
        { IconName.Share, FabricIcons.Share },
        { IconName.ShareAlt, FabricIcons.ShareiOS },
        { IconName.ShieldAlt, FabricIcons.ShieldSolid },
        //{ IconName.Ship, FabricIcons.Ship },
        { IconName.ShoppingBag, FabricIcons.Shop },
        { IconName.ShoppingBasket, FabricIcons.ShopServer },
        { IconName.ShoppingCart, FabricIcons.ShoppingCart },
        //{ IconName.ShuttleVan, FabricIcons.ShuttleVan },
        { IconName.SimCard, FabricIcons.SDCard },
        { IconName.SliderHorizontal, FabricIcons.Slider },
        { IconName.Smartphone, FabricIcons.CellPhone },
        { IconName.Smile, FabricIcons.Emoji2 },
        //{ IconName.Smoking, FabricIcons.Smoking },
        //{ IconName.SmokingBan, FabricIcons.SmokingBan },
        { IconName.Sms, FabricIcons.SkypeMessage },
        { IconName.Snowflake, FabricIcons.Snowflake },
        { IconName.Sort, FabricIcons.Sort },
        { IconName.SortAlphaDown, FabricIcons.SortLines },
        { IconName.SortAmountDownAlt, FabricIcons.SortLines },
        { IconName.SortDown, FabricIcons.SortDown },
        { IconName.SortUp, FabricIcons.SortUp },
        //{ IconName.Spa, FabricIcons.Spa },
        { IconName.SpellCheck, FabricIcons.Spelling },
        { IconName.Square, FabricIcons.SquareShape },
        { IconName.Star, FabricIcons.FavoriteStar },
        { IconName.StarHalf, FabricIcons.FavoriteStarFill },
        { IconName.StepBackward, FabricIcons.StepBackward },
        { IconName.StepForward, FabricIcons.Forward },
        { IconName.StickyNote, FabricIcons.QuickNote },
        { IconName.Stop, FabricIcons.Stop },
        { IconName.Store, FabricIcons.OfficeStoreLogo },
        { IconName.StoreAlt, FabricIcons.StoreLogo16 },
        { IconName.Stream, FabricIcons.Streaming },
        { IconName.StreetView, FabricIcons.Street },
        { IconName.Strikethrough, FabricIcons.Strikethrough },
        { IconName.Subscript, FabricIcons.Subscript },
        { IconName.Subway, FabricIcons.Train },
        { IconName.Suitcase, FabricIcons.Suitcase },
        { IconName.Sun, FabricIcons.Sunny },
        { IconName.Superscript, FabricIcons.Superscript },
        //{ IconName.SwimmingPool, FabricIcons.SwimmingPool },
        { IconName.Sync, FabricIcons.Sync },
        { IconName.SyncAlt, FabricIcons.SyncOccurence },
        { IconName.Tablet, FabricIcons.Tablet },
        { IconName.Tag, FabricIcons.Tag },
        { IconName.Taxi, FabricIcons.Taxi },
        { IconName.TextHeight, FabricIcons.FontSize2 },
        //{ IconName.ThumbsDown, FabricIcons.ThumbsDown },
        //{ IconName.ThumbsUp, FabricIcons.ThumbsUp },
        { IconName.TicketAlt, FabricIcons.Ticket },
        { IconName.Times, FabricIcons.Clear },
        //{ IconName.TimesCircle, FabricIcons.TimesCircle },
        { IconName.Tint, FabricIcons.Drop },
        { IconName.TintSlash, FabricIcons.DropShape },
        //{ IconName.TrafficLight, FabricIcons.TrafficLight },
        { IconName.Train, FabricIcons.Train },
        //{ IconName.Tram, FabricIcons.Tram },
        { IconName.Tree, FabricIcons.Street },
        { IconName.Truck, FabricIcons.DeliveryTruck },
        { IconName.Tv, FabricIcons.TVMonitor },
        { IconName.UmbrellaBeach, FabricIcons.Umbrella },
        { IconName.Underline, FabricIcons.Underline },
        { IconName.Undo, FabricIcons.Undo },
        { IconName.Unlock, FabricIcons.Unlock },
        { IconName.User, FabricIcons.Contact },
        { IconName.UserCheck, FabricIcons.UserFollowed },
        { IconName.UserCircle, FabricIcons.UserOptional },
        { IconName.UserFriends, FabricIcons.People },
        { IconName.UserPlus, FabricIcons.AddFriend },
        { IconName.Users, FabricIcons.People },
        //{ IconName.UserTie, FabricIcons.UserTie },
        //{ IconName.Utensils, FabricIcons.Utensils },
        { IconName.Video, FabricIcons.Video },
        { IconName.VideoSlash, FabricIcons.VideoOff },
        { IconName.Voicemail, FabricIcons.VoicemailForward },
        { IconName.VolumeDown, FabricIcons.Volume1 },
        { IconName.VolumeMute, FabricIcons.VolumeDisabled },
        { IconName.VolumeOff, FabricIcons.Volume0 },
        { IconName.VolumeUp, FabricIcons.Volume3 },
        //{ IconName.Walking, FabricIcons.Walking },
        //{ IconName.Wallet, FabricIcons.Wallet },
        { IconName.Wheelchair, FabricIcons.Wheelchair },
        { IconName.Wifi, FabricIcons.WifiEthernet },
        { IconName.WineBottle, FabricIcons.Wines },
        { IconName.Wrench, FabricIcons.Toolbox },
    };

    private static Dictionary<IconStyle, string> styles = new()
    {
        { IconStyle.Solid, "ms-Icon ms-Icon-filled" },
        { IconStyle.Regular, "ms-Icon ms-Icon-regular" },
        { IconStyle.Light, "ms-Icon ms-Icon-light" },
        { IconStyle.DuoTone, "ms-Icon ms-Icon-duo" },
    };

    #endregion

    #region Methods

    public override string IconSize( IconSize iconSize )
    {
        return iconSize switch
        {
            Blazorise.IconSize.ExtraSmall => "ms-Icon-xs",
            Blazorise.IconSize.Small => "ms-Icon-sm",
            Blazorise.IconSize.Large => "ms-Icon-lg",
            Blazorise.IconSize.x2 => "ms-Icon-2x",
            Blazorise.IconSize.x3 => "ms-Icon-3x",
            Blazorise.IconSize.x4 => "ms-Icon-4x",
            Blazorise.IconSize.x5 => "ms-Icon-5x",
            Blazorise.IconSize.x6 => "ms-Icon-6x",
            Blazorise.IconSize.x7 => "ms-Icon-7x",
            Blazorise.IconSize.x8 => "ms-Icon-8x",
            Blazorise.IconSize.x9 => "ms-Icon-9x",
            Blazorise.IconSize.x10 => "ms-Icon-10x",
            _ => null,
        };
    }

    public override string GetIconName( IconName iconName, IconStyle iconStyle )
    {
        names.TryGetValue( iconName, out var name );

        return name;
    }

    public override void SetIconName( IconName name, string newName )
    {
        names[name] = newName;
    }

    public override string GetStyleName( IconStyle iconStyle )
    {
        if ( styles.TryGetValue( iconStyle, out var style ) )
            return style;

        return null;
    }

    protected override bool ContainsStyleName( string iconName )
    {
        return iconName.Split( ' ' ).Any( x => styles.Values.Contains( x ) || new string[] { "ms-Icon-brand" }.Contains( x ) );
    }

    #endregion

    #region Properties

    public override bool IconNameAsContent => false;

    #endregion
}