#region Using directives
using System;
using System.Collections.Generic;
using Blazorise;
#endregion

namespace Blazorise.Pdf;

/// <summary>
/// Describes a PDF document that can be generated by an <see cref="IPdfGenerator"/>.
/// </summary>
public sealed class PdfDocumentDefinition
{
    #region Methods

    /// <summary>
    /// Adds a document-scoped font family.
    /// </summary>
    /// <param name="font">Font family.</param>
    /// <returns>The document definition.</returns>
    public PdfDocumentDefinition AddFont( FontFamily font )
    {
        if ( string.IsNullOrWhiteSpace( font?.Name ) )
            return this;

        Fonts ??= [];

        int existingIndex = Fonts.FindIndex( x => string.Equals( x.Name, font.Name, StringComparison.OrdinalIgnoreCase ) );

        if ( existingIndex >= 0 )
            Fonts[existingIndex] = font;
        else
            Fonts.Add( font );

        return this;
    }

    /// <summary>
    /// Adds a document-scoped font family.
    /// </summary>
    /// <param name="name">Font family name.</param>
    /// <param name="regular">Regular font source.</param>
    /// <returns>The document definition.</returns>
    public PdfDocumentDefinition AddFont( string name, FontSource regular )
    {
        return AddFont( name, regular, null, null, null );
    }

    /// <summary>
    /// Adds a document-scoped font family.
    /// </summary>
    /// <param name="name">Font family name.</param>
    /// <param name="regular">Regular font source.</param>
    /// <param name="bold">Bold font source.</param>
    /// <param name="italic">Italic font source.</param>
    /// <param name="boldItalic">Bold italic font source.</param>
    /// <returns>The document definition.</returns>
    public PdfDocumentDefinition AddFont( string name, FontSource regular, FontSource bold = null, FontSource italic = null, FontSource boldItalic = null )
    {
        return AddFont( new()
        {
            Name = name,
            Regular = regular,
            Bold = bold,
            Italic = italic,
            BoldItalic = boldItalic,
        } );
    }

    #endregion

    #region Properties

    /// <summary>
    /// Document title metadata.
    /// </summary>
    public string Title { get; set; }

    /// <summary>
    /// Default page size used by pages that do not specify their own dimensions.
    /// </summary>
    public PdfPageSize PageSize { get; set; } = PdfPageSize.A4;

    /// <summary>
    /// Default page orientation used by pages that do not specify their own orientation.
    /// </summary>
    public PdfOrientation Orientation { get; set; } = PdfOrientation.Portrait;

    /// <summary>
    /// Default page width in points.
    /// </summary>
    public double PageWidth { get; set; } = PdfPageMetrics.A4Width;

    /// <summary>
    /// Default page height in points.
    /// </summary>
    public double PageHeight { get; set; } = PdfPageMetrics.A4Height;

    /// <summary>
    /// Pages included in the document.
    /// </summary>
    public List<PdfPageDefinition> Pages { get; set; } = [];

    /// <summary>
    /// Document-scoped font families resolved before globally registered fonts.
    /// </summary>
    public List<FontFamily> Fonts { get; set; } = [];

    #endregion
}

/// <summary>
/// Describes one PDF page.
/// </summary>
public sealed class PdfPageDefinition
{
    #region Properties

    /// <summary>
    /// Page size used by this page.
    /// </summary>
    public PdfPageSize Size { get; set; } = PdfPageSize.Custom;

    /// <summary>
    /// Page orientation used by this page.
    /// </summary>
    public PdfOrientation Orientation { get; set; } = PdfOrientation.Portrait;

    /// <summary>
    /// Page width in points.
    /// </summary>
    public double Width { get; set; } = PdfPageMetrics.A4Width;

    /// <summary>
    /// Page height in points.
    /// </summary>
    public double Height { get; set; } = PdfPageMetrics.A4Height;

    /// <summary>
    /// Elements rendered on the page.
    /// </summary>
    public List<PdfElementDefinition> Elements { get; set; } = [];

    #endregion
}

/// <summary>
/// Describes a PDF element.
/// </summary>
public sealed class PdfElementDefinition
{
    #region Properties

    /// <summary>
    /// Element kind.
    /// </summary>
    public PdfElementType Type { get; set; }

    /// <summary>
    /// Horizontal element position in points.
    /// </summary>
    public double X { get; set; }

    /// <summary>
    /// Vertical element position in points.
    /// </summary>
    public double Y { get; set; }

    /// <summary>
    /// Element width in points.
    /// </summary>
    public double Width { get; set; }

    /// <summary>
    /// Element height in points.
    /// </summary>
    public double Height { get; set; }

    /// <summary>
    /// Text content rendered by text-like elements.
    /// </summary>
    public string Text { get; set; }

    /// <summary>
    /// Indicates that text should wrap inside the element bounds.
    /// </summary>
    public bool Wrap { get; set; } = true;

    /// <summary>
    /// Image source used by image elements.
    /// </summary>
    public string Source { get; set; }

    /// <summary>
    /// Defines how the image fits inside the element bounds.
    /// </summary>
    public PdfImageFit ImageFit { get; set; } = PdfImageFit.Fill;

    /// <summary>
    /// Font settings used by text-like elements.
    /// </summary>
    public PdfFontDefinition Font { get; set; } = new();

    /// <summary>
    /// Border settings used by shape-like elements.
    /// </summary>
    public PdfBorderDefinition Border { get; set; } = new();

    /// <summary>
    /// Appearance settings used by filled elements.
    /// </summary>
    public PdfAppearanceDefinition Appearance { get; set; } = new();

    /// <summary>
    /// Table rows used by table elements.
    /// </summary>
    public List<PdfTableRowDefinition> Rows { get; set; } = [];

    #endregion
}

/// <summary>
/// Describes PDF font styling.
/// </summary>
public sealed class PdfFontDefinition
{
    #region Properties

    /// <summary>
    /// Font family name. The built-in renderer maps the family to the closest PDF standard font (Helvetica, Times, or Courier).
    /// </summary>
    public string Family { get; set; } = "Helvetica";

    /// <summary>
    /// Font size in points.
    /// </summary>
    public double Size { get; set; } = 12;

    /// <summary>
    /// Text color as a hex color value.
    /// </summary>
    public string Color { get; set; } = "#000000";

    /// <summary>
    /// Text alignment inside the element bounds.
    /// </summary>
    /// <remarks>
    /// <see cref="TextAlignment.Default"/> and <see cref="TextAlignment.Start"/> align to the start.
    /// <see cref="TextAlignment.Justified"/> distributes words across wrapped non-final paragraph lines.
    /// </remarks>
    public TextAlignment Alignment { get; set; }

    /// <summary>
    /// Text vertical alignment inside the element bounds.
    /// </summary>
    /// <remarks>
    /// <see cref="VerticalAlignment.Default"/>, <see cref="VerticalAlignment.Baseline"/>,
    /// <see cref="VerticalAlignment.Top"/>, and <see cref="VerticalAlignment.TextTop"/> align to the top.
    /// <see cref="VerticalAlignment.Middle"/> centers the text, while <see cref="VerticalAlignment.Bottom"/>
    /// and <see cref="VerticalAlignment.TextBottom"/> align to the bottom.
    /// </remarks>
    public VerticalAlignment VerticalAlignment { get; set; }

    /// <summary>
    /// Indicates that text should be rendered bold when supported by the renderer.
    /// </summary>
    public bool Bold { get; set; }

    /// <summary>
    /// Indicates that text should be rendered italic when supported by the renderer.
    /// </summary>
    public bool Italic { get; set; }

    #endregion
}

/// <summary>
/// Describes PDF border styling.
/// </summary>
public sealed class PdfBorderDefinition
{
    #region Properties

    /// <summary>
    /// Border color as a hex color value.
    /// </summary>
    public string Color { get; set; } = "#000000";

    /// <summary>
    /// Border width in points.
    /// </summary>
    public double Width { get; set; } = 1;

    /// <summary>
    /// Border line style.
    /// </summary>
    public PdfBorderStyle Style { get; set; }

    #endregion
}

/// <summary>
/// Describes PDF fill styling.
/// </summary>
public sealed class PdfAppearanceDefinition
{
    #region Properties

    /// <summary>
    /// Fill color as a hex color value.
    /// </summary>
    public string BackgroundColor { get; set; }

    #endregion
}

/// <summary>
/// Describes a PDF table row.
/// </summary>
public sealed class PdfTableRowDefinition
{
    #region Properties

    /// <summary>
    /// Row height in points.
    /// </summary>
    public double Height { get; set; } = 24;

    /// <summary>
    /// Cells included in the row.
    /// </summary>
    public List<PdfTableCellDefinition> Cells { get; set; } = [];

    #endregion
}

/// <summary>
/// Describes a PDF table cell.
/// </summary>
public sealed class PdfTableCellDefinition
{
    #region Properties

    /// <summary>
    /// Cell width in points.
    /// </summary>
    public double Width { get; set; } = 90;

    /// <summary>
    /// Elements rendered inside the cell.
    /// </summary>
    public List<PdfElementDefinition> Elements { get; set; } = [];

    #endregion
}