#region Using directives
using System.Collections.Generic;
#endregion

namespace Blazorise.Pdf;

/// <summary>
/// Describes a PDF document that can be generated by an <see cref="IPdfGenerator"/>.
/// </summary>
public sealed class PdfDocumentDefinition
{
    #region Properties

    /// <summary>
    /// Document title metadata.
    /// </summary>
    public string Title { get; set; }

    /// <summary>
    /// Default page size used by pages that do not specify their own dimensions.
    /// </summary>
    public PdfPageSize PageSize { get; set; } = PdfPageSize.A4;

    /// <summary>
    /// Default page orientation used by pages that do not specify their own orientation.
    /// </summary>
    public PdfOrientation Orientation { get; set; } = PdfOrientation.Portrait;

    /// <summary>
    /// Default page width in points.
    /// </summary>
    public double PageWidth { get; set; } = PdfPageMetrics.A4Width;

    /// <summary>
    /// Default page height in points.
    /// </summary>
    public double PageHeight { get; set; } = PdfPageMetrics.A4Height;

    /// <summary>
    /// Pages included in the document.
    /// </summary>
    public List<PdfPageDefinition> Pages { get; set; } = [];

    #endregion
}

/// <summary>
/// Describes one PDF page.
/// </summary>
public sealed class PdfPageDefinition
{
    #region Properties

    /// <summary>
    /// Page size used by this page.
    /// </summary>
    public PdfPageSize Size { get; set; } = PdfPageSize.Custom;

    /// <summary>
    /// Page orientation used by this page.
    /// </summary>
    public PdfOrientation Orientation { get; set; } = PdfOrientation.Portrait;

    /// <summary>
    /// Page width in points.
    /// </summary>
    public double Width { get; set; } = PdfPageMetrics.A4Width;

    /// <summary>
    /// Page height in points.
    /// </summary>
    public double Height { get; set; } = PdfPageMetrics.A4Height;

    /// <summary>
    /// Elements rendered on the page.
    /// </summary>
    public List<PdfElementDefinition> Elements { get; set; } = [];

    #endregion
}

/// <summary>
/// Describes a PDF element.
/// </summary>
public sealed class PdfElementDefinition
{
    #region Properties

    /// <summary>
    /// Element kind.
    /// </summary>
    public PdfElementType Type { get; set; }

    /// <summary>
    /// Horizontal element position in points.
    /// </summary>
    public double X { get; set; }

    /// <summary>
    /// Vertical element position in points.
    /// </summary>
    public double Y { get; set; }

    /// <summary>
    /// Element width in points.
    /// </summary>
    public double Width { get; set; }

    /// <summary>
    /// Element height in points.
    /// </summary>
    public double Height { get; set; }

    /// <summary>
    /// Text content rendered by text-like elements.
    /// </summary>
    public string Text { get; set; }

    /// <summary>
    /// Image source used by image elements.
    /// </summary>
    public string Source { get; set; }

    /// <summary>
    /// Defines how the image fits inside the element bounds.
    /// </summary>
    public PdfImageFit ImageFit { get; set; } = PdfImageFit.Fill;

    /// <summary>
    /// Font settings used by text-like elements.
    /// </summary>
    public PdfFontDefinition Font { get; set; } = new();

    /// <summary>
    /// Border settings used by shape-like elements.
    /// </summary>
    public PdfBorderDefinition Border { get; set; } = new();

    /// <summary>
    /// Appearance settings used by filled elements.
    /// </summary>
    public PdfAppearanceDefinition Appearance { get; set; } = new();

    /// <summary>
    /// Table rows used by table elements.
    /// </summary>
    public List<PdfTableRowDefinition> Rows { get; set; } = [];

    #endregion
}

/// <summary>
/// Describes PDF font styling.
/// </summary>
public sealed class PdfFontDefinition
{
    #region Properties

    /// <summary>
    /// Font family name. The built-in renderer maps the family to the closest PDF standard font (Helvetica, Times, or Courier).
    /// </summary>
    public string Family { get; set; } = "Helvetica";

    /// <summary>
    /// Font size in points.
    /// </summary>
    public double Size { get; set; } = 12;

    /// <summary>
    /// Text color as a hex color value.
    /// </summary>
    public string Color { get; set; } = "#000000";

    /// <summary>
    /// Text alignment inside the element bounds.
    /// </summary>
    public PdfTextAlignment Alignment { get; set; }

    /// <summary>
    /// Text vertical alignment inside the element bounds.
    /// </summary>
    public PdfVerticalAlignment VerticalAlignment { get; set; }

    /// <summary>
    /// Indicates that text should be rendered bold when supported by the renderer.
    /// </summary>
    public bool Bold { get; set; }

    /// <summary>
    /// Indicates that text should be rendered italic when supported by the renderer.
    /// </summary>
    public bool Italic { get; set; }

    #endregion
}

/// <summary>
/// Describes PDF border styling.
/// </summary>
public sealed class PdfBorderDefinition
{
    #region Properties

    /// <summary>
    /// Border color as a hex color value.
    /// </summary>
    public string Color { get; set; } = "#000000";

    /// <summary>
    /// Border width in points.
    /// </summary>
    public double Width { get; set; } = 1;

    /// <summary>
    /// Border line style.
    /// </summary>
    public PdfBorderStyle Style { get; set; }

    #endregion
}

/// <summary>
/// Describes PDF fill styling.
/// </summary>
public sealed class PdfAppearanceDefinition
{
    #region Properties

    /// <summary>
    /// Fill color as a hex color value.
    /// </summary>
    public string BackgroundColor { get; set; }

    #endregion
}

/// <summary>
/// Describes a PDF table row.
/// </summary>
public sealed class PdfTableRowDefinition
{
    #region Properties

    /// <summary>
    /// Row height in points.
    /// </summary>
    public double Height { get; set; } = 24;

    /// <summary>
    /// Cells included in the row.
    /// </summary>
    public List<PdfTableCellDefinition> Cells { get; set; } = [];

    #endregion
}

/// <summary>
/// Describes a PDF table cell.
/// </summary>
public sealed class PdfTableCellDefinition
{
    #region Properties

    /// <summary>
    /// Cell width in points.
    /// </summary>
    public double Width { get; set; } = 90;

    /// <summary>
    /// Elements rendered inside the cell.
    /// </summary>
    public List<PdfElementDefinition> Elements { get; set; } = [];

    #endregion
}