#region Using directives
using System;
using System.Collections.Generic;
using Blazorise;
#endregion

namespace Blazorise.Pdf;

/// <summary>
/// Describes a PDF document that can be generated by an <see cref="IPdfGenerator"/>.
/// </summary>
public sealed class PdfDocumentDefinition
{
    #region Methods

    /// <summary>
    /// Adds a document-scoped font family.
    /// </summary>
    /// <param name="font">Font family.</param>
    /// <returns>The document definition.</returns>
    public PdfDocumentDefinition AddFont( FontFamily font )
    {
        if ( string.IsNullOrWhiteSpace( font?.Name ) )
            return this;

        Fonts ??= [];

        int existingIndex = Fonts.FindIndex( x => string.Equals( x.Name, font.Name, StringComparison.OrdinalIgnoreCase ) );

        if ( existingIndex >= 0 )
            Fonts[existingIndex] = font;
        else
            Fonts.Add( font );

        return this;
    }

    /// <summary>
    /// Adds a document-scoped font family.
    /// </summary>
    /// <param name="name">Font family name.</param>
    /// <param name="regular">Regular font source.</param>
    /// <returns>The document definition.</returns>
    public PdfDocumentDefinition AddFont( string name, FontSource regular )
    {
        return AddFont( name, regular, null, null, null );
    }

    /// <summary>
    /// Adds a document-scoped font family.
    /// </summary>
    /// <param name="name">Font family name.</param>
    /// <param name="regular">Regular font source.</param>
    /// <param name="bold">Bold font source.</param>
    /// <param name="italic">Italic font source.</param>
    /// <param name="boldItalic">Bold italic font source.</param>
    /// <returns>The document definition.</returns>
    public PdfDocumentDefinition AddFont( string name, FontSource regular, FontSource bold = null, FontSource italic = null, FontSource boldItalic = null )
    {
        return AddFont( new()
        {
            Name = name,
            Regular = regular,
            Bold = bold,
            Italic = italic,
            BoldItalic = boldItalic,
        } );
    }

    #endregion

    #region Properties

    /// <summary>
    /// Document title metadata.
    /// </summary>
    public string Title { get; set; }

    /// <summary>
    /// Default page size used by pages that do not specify their own dimensions.
    /// </summary>
    public PdfPageSize PageSize { get; set; } = PdfPageSize.A4;

    /// <summary>
    /// Default page orientation used by pages that do not specify their own orientation.
    /// </summary>
    public PdfOrientation Orientation { get; set; } = PdfOrientation.Portrait;

    /// <summary>
    /// Default page width in points.
    /// </summary>
    public double PageWidth { get; set; } = PdfPageMetrics.A4Width;

    /// <summary>
    /// Default page height in points.
    /// </summary>
    public double PageHeight { get; set; } = PdfPageMetrics.A4Height;

    /// <summary>
    /// Pages included in the document.
    /// </summary>
    public List<PdfPageDefinition> Pages { get; set; } = [];

    /// <summary>
    /// Document-scoped font families resolved before globally registered fonts.
    /// </summary>
    public List<FontFamily> Fonts { get; set; } = [];

    #endregion
}