name: NuGet Build

on:
  create:
    tags: v0.9.*, v1.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Echo - Version Tag
      run: echo 'The tag was ${{ GITHUB_REF }}.'
