name: NuGet Build

on:
  push:
    tags:
      - '1.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
          
    - name: Echo - Latest Version Tag
      id: latest_tag
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore NuGet Packages
      run: dotnet restore
      
    - name: Build - Release
      run: dotnet build --configuration Release --no-restore /p:Version=$VERSION
      env:
        VERSION: ${{ steps.latest_tag.outputs.VERSION }}
      
    - name: Run Unit Tests - Release
      run: dotnet test ./Tests/Blazorise.Tests/Blazorise.Tests.csproj --configuration Release --no-restore --no-build --verbosity normal

    - name: Prepare E2E Tests Dependencies 
      run: pwsh ./Tests/Blazorise.E2E.Tests/bin/Release/net8.0/playwright.ps1 install --with-deps

    - name: Run E2E Tests - Release
      run: dotnet test ./Tests/Blazorise.E2E.Tests/Blazorise.E2E.Tests.csproj --configuration Release --no-restore --no-build --verbosity normal

    - name: Pack - Release
      run: dotnet pack --configuration Release --no-restore -o ./Packages /p:Version=$VERSION /p:PackageVersion=$VERSION
      env:
        VERSION: ${{ steps.latest_tag.outputs.VERSION }}
    
    - name: Push - Release
      run: dotnet nuget push ./Packages/ -s https://www.myget.org/F/blazorise/api/v3/index.json -k ${{ secrets.MYGET_API_KEY }}

    - name: Upload Blazorise.Components
      uses: actions/upload-artifact@v1
      with:
        name: Blazorise-Packages
        path: ./Packages/
