name: Blazorise Library Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200

    - name: Restore NuGet Packages
      run: dotnet restore
      
    - name: Build - Release
      run: dotnet build --configuration Release --no-restore
      
    - name: Run Unit Tests - Release
      run: dotnet test ./Tests/Blazorise.Tests/Blazorise.Tests.csproj --configuration Release --no-restore --no-build --verbosity normal

    - name: Publish - Release
      run: dotnet publish --configuration Release --no-restore --no-build

    - name: Upload Blazorise
      uses: actions/upload-artifact@v1
      with:
        name: Blazorise.zip
        path: ./Source/Blazorise/bin/Release/netstandard2.1/publish/
        
    - name: Upload Blazorise.Components
      uses: actions/upload-artifact@v1
      with:
        name: Blazorise.Components.zip, 
        path: ./Source/Blazorise.Components/bin/Release/netstandard2.1/publish/

    - name: Upload Blazorise.DataGrid
      uses: actions/upload-artifact@v1
      with:
        name: Blazorise.DataGrid.zip
        path: ./Source/Blazorise.DataGrid/bin/Release/netstandard2.1/publish/

    - name: Upload Blazorise.Sidebar
      uses: actions/upload-artifact@v1
      with:
        name: Blazorise.Sidebar.zip
        path: ./Source/Blazorise.Sidebar/bin/Release/netstandard2.1/publish/

    - name: Upload Blazorise.Charts
      uses: actions/upload-artifact@v1
      with:
        name: Blazorise.Charts.zip
        path: ./Source/Blazorise.Charts/bin/Release/netstandard2.1/publish/

    - name: Upload Blazorise.Snackbar
      uses: actions/upload-artifact@v1
      with:
        name: Blazorise.Snackbar.zip
        path: ./Source/Blazorise.Snackbar/bin/Release/netstandard2.1/publish/

    - name: Upload Blazorise.Frolic
      uses: actions/upload-artifact@v1
      with:
        name: Blazorise.Frolic.zip
        path: ./Source/Blazorise.Frolic/bin/Release/netstandard2.1/publish/

    - name: Upload Blazorise.Bulma
      uses: actions/upload-artifact@v1
      with:
        name: Blazorise.Bulma.zip
        path: ./Source/Blazorise.Bulma/bin/Release/netstandard2.1/publish/

    - name: Upload Blazorise.Bootstrap
      uses: actions/upload-artifact@v1
      with:
        name: Blazorise.Bootstrap.zip
        path: ./Source/Blazorise.Bootstrap/bin/Release/netstandard2.1/publish/

    - name: Upload Blazorise.Icons.FontAwesome
      uses: actions/upload-artifact@v1
      with:
        name: Blazorise.Icons.FontAwesome.zip
        path: ./Source/Blazorise.Icons.FontAwesome/bin/Release/netstandard2.1/publish/

    - name: Upload Blazorise.Icons.Material
      uses: actions/upload-artifact@v1
      with:
        name: Blazorise.Icons.Material.zip
        path: ./Source/Blazorise.Icons.Material/bin/Release/netstandard2.1/publish/

    - name: Upload Blazorise.Material
      uses: actions/upload-artifact@v1
      with:
        name: Blazorise.Material.zip
        path: ./Source/Blazorise.Material/bin/Release/netstandard2.1/publish/

    - name: Upload Blazorise.AntDesign
      uses: actions/upload-artifact@v1
      with:
        name: Blazorise.AntDesign.zip
        path: ./Source/Blazorise.AntDesign/bin/Release/netstandard2.1/publish/

    - name: Upload Blazorise.Charts.Streaming
      uses: actions/upload-artifact@v1
      with:
        name: Blazorise.Charts.Streaming.zip
        path: ./Source/Blazorise.Charts.Streaming/bin/Release/netstandard2.1/publish/
